import { StyleSheet } from 'react-native';
import { colors, spacing, typography } from '../../theme';

export default StyleSheet.create({

  content: {
    paddingVertical: spacing.xl,
  },
  mainContent: {
    marginTop: spacing.md,
    paddingBottom: spacing.xl,
  },
  scrollContent: {
    alignItems: 'center',
    paddingBottom: 40,
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  logo: {
    width: 120,
    height: 120,
    marginBottom: spacing.md,
    resizeMode: 'contain',
  },
  title: {
    fontSize: typography.fontSize.xl,
    color: '#FFF',
    fontWeight: typography.fontWeight.bold as any,
    marginBottom: spacing.md,
    alignSelf: 'flex-start',
  },
  instructions: {
    color: colors.white,
    fontSize: 16,
    fontWeight: typography.fontWeight.medium,
    marginTop: spacing.lg,
    marginBottom: spacing.xl,
    alignSelf: 'flex-start',
  },
  paymentMethodsContainer: {
    width: '100%',
    gap: spacing.lg,
  },
  paymentMethodCard: {
    backgroundColor: colors.white5,
    borderRadius: 16,
    padding: spacing.lg,
    alignItems: 'center',
  },
  paymentMethodIcon: {
    marginBottom: spacing.md,
    height: 100,
    width: 170,
    objectFit: 'contain',
  },
  paymentMethodTitle: {
    color: colors.white,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.semibold,
    marginBottom: spacing.sm,
    textAlign: 'center',
  },
  paymentMethodDescription: {
    color: colors.white70,
    fontSize: 14,
    fontWeight: typography.fontWeight.regular,
    textAlign: 'center',
    lineHeight: 20,
  },
  // WebView Styles
  webViewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#181818',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#2A2A2A',
  },
  webViewBackButton: {
    padding: 8,
  },
  webViewTitle: {
    color: '#FFF',
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.bold as any,
  },
  webViewCloseButton: {
    padding: 8,
  },
  webViewContainer: {
    flex: 1,
    position: 'relative',
  },
  webView: {
    flex: 1,
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#181818',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  loadingText: {
    color: '#FFF',
    fontSize: typography.fontSize.md,
  },
  errorOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#181818',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
    padding: 20,
  },
  errorText: {
    color: '#FF6B6B',
    fontSize: typography.fontSize.lg,
    marginBottom: 20,
    textAlign: 'center',
  },
  retryButton: {
    backgroundColor: '#A5EA15',
    borderRadius: 8,
    paddingHorizontal: 20,
    paddingVertical: 12,
    marginBottom: 12,
    minWidth: 120,
  },
  retryButtonText: {
    color: '#212121',
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.bold as any,
    textAlign: 'center',
  },
  backButton: {
    backgroundColor: '#2A2A2A',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#A5EA15',
    paddingHorizontal: 20,
    paddingVertical: 12,
    minWidth: 120,
  },
  backButtonText: {
    color: '#A5EA15',
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium as any,
    textAlign: 'center',
  },
  connectionStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2A2A2A',
    borderRadius: 12,
    padding: 16,
    marginBottom: spacing.lg,
    width: '100%',
    justifyContent: 'center',
  },
  connectedIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#A5EA15',
    marginRight: 8,
  },
  disconnectedIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FF6B6B',
    marginRight: 8,
  },
  walletSourceText: {
    color: '#FFF',
    fontSize: typography.fontSize.sm,
    marginLeft: 8,
    fontWeight: typography.fontWeight.medium as any,
  },
  amountSection: {
    width: '100%',
    marginBottom: spacing.lg,
  },
  amountLabel: {
    color: '#FFF',
    fontSize: typography.fontSize.md,
    marginBottom: 8,
    fontWeight: typography.fontWeight.medium as any,
  },
  amountInput: {
    backgroundColor: '#2A2A2A',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#A5EA15',
    padding: 12,
    color: '#A5EA15',
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.bold as any,
    textAlign: 'center',
    width: '100%',
  },
  prefillNote: {
    color: '#A89B9B',
    fontSize: typography.fontSize.sm,
    textAlign: 'center',
    fontStyle: 'italic',
    marginBottom: spacing.sm,
  },
  errorText: {
    color: '#FF6B6B',
    fontSize: typography.fontSize.md,
  },
  createWalletBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2A2A2A',
    borderRadius: 8,
    padding: 12,
    width: '100%',
    justifyContent: 'center',
    marginBottom: spacing.lg,
  },
  createWalletText: {
    color: '#A5EA15',
    fontSize: typography.fontSize.sm,
    marginLeft: 4,
    fontWeight: typography.fontWeight.medium as any,
  },
  addressBox: {
    backgroundColor: '#2A2A2A',
    borderRadius: 12,
    paddingHorizontal: spacing.lg,
    marginBottom: spacing.lg,
    width: '100%',
    alignItems: 'center',
  },
  addressLabel: {
    color: colors.white70,
    fontSize: typography.fontSize.sm,
    marginBottom: 4,
    fontWeight: typography.fontWeight.regular,
  },
  addressValue: {
    color: colors.white,
    fontSize: typography.fontSize.xl,
    lineHeight: 30,
    fontFamily: 'monospace',
    marginBottom: spacing.sm,
    textAlign: 'center',
    paddingHorizontal: spacing.lg,

  },
  qrSection: {
    alignItems: 'center',
    marginBottom: spacing.md,
    width: '100%',
    justifyContent: 'center',
  },
  qrContainer: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 30,
    padding: spacing.lg,
    borderWidth: 5,
    
  },
  copyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#A5EA15',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginTop: spacing.sm,
  },
  copyButtonSecondary: {
    backgroundColor: '#2A2A2A',
    borderColor: '#A5EA15',
    borderWidth: 1,
  },
  actionText: {
    color: '#A5EA15',
    fontSize: typography.fontSize.sm,
    marginLeft: 4,
    fontWeight: typography.fontWeight.medium as any,
  },
  actionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    marginTop: spacing.md,
  },
  actionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#A5EA15',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  fundingButtons: {
    width: '100%',
    marginBottom: spacing.lg,
  },
  moonpayButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#A5EA15',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    justifyContent: 'center',
  },
  moonpayButtonSecondary: {
    backgroundColor: '#2A2A2A',
    borderColor: '#A5EA15',
    borderWidth: 1,
  },
  moonpayButtonText: {
    color: '#212121',
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium as any,
    marginLeft: 8,
  },
  directFundButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2A2A2A',
    borderRadius: 12,
    borderColor: '#A5EA15',
    borderWidth: 1,
    padding: 16,
    justifyContent: 'center',
  },
  directFundButtonText: {
    color: '#FFF',
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium as any,
    marginLeft: 8,
  },
  disabledButton: {
    opacity: 0.5,
  },
  tipBox: {
    backgroundColor: colors.white10,
    borderRadius: 12,
    padding: spacing.lg,
    width: '100%',
  },
  tipTitle: {
    color: colors.green,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.bold as any,
    marginBottom: 4,
  },
  tipText: {
    color: colors.white70,
    fontSize: typography.fontSize.sm,
    lineHeight: 20,
    fontWeight: typography.fontWeight.regular,
  },
  walletSourceIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2A2A2A',
    borderRadius: 12,
    padding: 16,
    marginBottom: spacing.lg,
    width: '100%',
    justifyContent: 'center',
  },
  scrollView: {
    flex: 1,
  },
  // Header styles
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.white,
  },
  placeholder: {
    width: 40,
  },
  // New styles for the updated design
  addressDisplay: {
    alignItems: 'center',
    marginBottom: spacing.lg,
  },
  actionButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    marginBottom: spacing.lg,
  },
  actionButton: {
    backgroundColor: '#A5EA15',
    borderRadius: 16,
    paddingHorizontal: 20,
    paddingVertical: 12,
    minWidth: 100,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    width: '45%',
  },
  actionButtonText: {
    color: '#212121',
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium as any,
    marginLeft: 8,
  },
  doneButton: {
    backgroundColor: colors.black,
    borderWidth: 1,
    borderColor: colors.green,
    borderRadius: 12,
    padding: 16,
    marginTop: spacing.lg,
    alignItems: 'center',
    width: '100%',
  },
  doneButtonText: {
    color: colors.green,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.bold as any,
  },
  // Transfer section styles
  transferSection: {
    backgroundColor: colors.white10,
    borderRadius: 16,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    width: '100%',
  },
  sectionTitle: {
    color: colors.white,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.bold as any,
    marginBottom: spacing.sm,
    textAlign: 'center',
  },
  sectionDescription: {
    color: colors.white70,
    fontSize: typography.fontSize.sm,
    textAlign: 'center',
    marginBottom: spacing.lg,
    lineHeight: 20,
  },
  externalWalletInfo: {
    backgroundColor: '#2A2A2A',
    borderRadius: 12,
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  appWalletInfo: {
    backgroundColor: '#2A2A2A',
    borderRadius: 12,
    padding: spacing.md,
    marginBottom: spacing.lg,
  },
  walletLabel: {
    color: colors.white70,
    fontSize: typography.fontSize.sm,
    marginBottom: 4,
    fontWeight: typography.fontWeight.medium as any,
  },
  walletAddress: {
    color: colors.white,
    fontSize: typography.fontSize.md,
    fontFamily: 'monospace',
    marginBottom: 4,
  },
  balanceText: {
    color: colors.green,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium as any,
  },
  transferAmountInput: {
    marginBottom: spacing.lg,
  },
  transferAmountLabel: {
    color: colors.white,
    fontSize: typography.fontSize.md,
    marginBottom: spacing.sm,
    fontWeight: typography.fontWeight.medium as any,
  },
  input: {
    backgroundColor: '#2A2A2A',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.green,
    padding: 12,
    color: colors.white,
    fontSize: typography.fontSize.lg,
    textAlign: 'center',
  },
  transferButton: {
    backgroundColor: colors.green,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    width: '100%',
  },
  transferButtonDisabled: {
    opacity: 0.5,
  },
  transferButtonText: {
    color: colors.black,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.bold as any,
  },
  divider: {
    height: 1,
    backgroundColor: colors.white10,
    marginVertical: spacing.lg,
    width: '100%',
  },
  scrollViewContent: {
    flexGrow: 1,
    paddingBottom: spacing.xl,
    minHeight: '100%',
  },
}); 