import { StyleSheet } from 'react-native';
import { colors, spacing, typography } from '../../theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#181818',
    paddingHorizontal: 20,
    paddingTop: 40,
  },
  scrollContent: {
    alignItems: 'center',
    paddingBottom: 40,
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  logo: {
    width: 120,
    height: 120,
    marginBottom: spacing.md,
    resizeMode: 'contain',
  },
  title: {
    fontSize: typography.fontSize.xl,
    color: '#FFF',
    fontWeight: typography.fontWeight.bold as any,
    marginBottom: spacing.md,
    alignSelf: 'flex-start',
  },
  instructions: {
    color: '#A89B9B',
    fontSize: typography.fontSize.md,
    marginBottom: spacing.lg,
    alignSelf: 'flex-start',
  },
  connectionStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2A2A2A',
    borderRadius: 12,
    padding: 16,
    marginBottom: spacing.lg,
    width: '100%',
    justifyContent: 'center',
  },
  connectedIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#A5EA15',
    marginRight: 8,
  },
  disconnectedIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FF6B6B',
    marginRight: 8,
  },
  walletSourceText: {
    color: '#FFF',
    fontSize: typography.fontSize.sm,
    marginLeft: 8,
    fontWeight: typography.fontWeight.medium as any,
  },
  amountSection: {
    width: '100%',
    marginBottom: spacing.lg,
  },
  amountLabel: {
    color: '#FFF',
    fontSize: typography.fontSize.md,
    marginBottom: 8,
    fontWeight: typography.fontWeight.medium as any,
  },
  amountInput: {
    backgroundColor: '#2A2A2A',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#A5EA15',
    padding: 12,
    color: '#A5EA15',
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.bold as any,
    textAlign: 'center',
    width: '100%',
  },
  prefillNote: {
    color: '#A89B9B',
    fontSize: typography.fontSize.sm,
    textAlign: 'center',
    fontStyle: 'italic',
    marginBottom: spacing.sm,
  },
  errorText: {
    color: '#FF6B6B',
    fontSize: typography.fontSize.md,
  },
  createWalletBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2A2A2A',
    borderRadius: 8,
    padding: 12,
    width: '100%',
    justifyContent: 'center',
    marginBottom: spacing.lg,
  },
  createWalletText: {
    color: '#A5EA15',
    fontSize: typography.fontSize.sm,
    marginLeft: 4,
    fontWeight: typography.fontWeight.medium as any,
  },
  addressBox: {
    backgroundColor: '#2A2A2A',
    borderRadius: 12,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    width: '100%',
    alignItems: 'center',
  },
  addressLabel: {
    color: '#A89B9B',
    fontSize: typography.fontSize.sm,
    marginBottom: 4,
  },
  addressValue: {
    color: '#A5EA15',
    fontSize: typography.fontSize.md,
    fontFamily: 'monospace',
    marginBottom: spacing.sm,
    textAlign: 'center',
  },
  qrSection: {
    alignItems: 'center',
    backgroundColor: '#212121',
    borderRadius: 12,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    width: '100%',
  },
  copyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#A5EA15',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginTop: spacing.sm,
  },
  copyButtonSecondary: {
    backgroundColor: '#2A2A2A',
    borderColor: '#A5EA15',
    borderWidth: 1,
  },
  actionText: {
    color: '#A5EA15',
    fontSize: typography.fontSize.sm,
    marginLeft: 4,
    fontWeight: typography.fontWeight.medium as any,
  },
  fundingButtons: {
    width: '100%',
    marginBottom: spacing.lg,
  },
  moonpayButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#A5EA15',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    justifyContent: 'center',
  },
  moonpayButtonText: {
    color: '#212121',
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium as any,
    marginLeft: 8,
  },
  directFundButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2A2A2A',
    borderRadius: 12,
    borderColor: '#A5EA15',
    borderWidth: 1,
    padding: 16,
    justifyContent: 'center',
  },
  directFundButtonText: {
    color: '#FFF',
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium as any,
    marginLeft: 8,
  },
  tipBox: {
    backgroundColor: '#2A2A2A',
    borderRadius: 12,
    padding: spacing.lg,
    width: '100%',
  },
  tipTitle: {
    color: '#A5EA15',
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.bold as any,
    marginBottom: 4,
  },
  tipText: {
    color: '#A89B9B',
    fontSize: typography.fontSize.sm,
    lineHeight: 20,
  },
}); 