import { StyleSheet } from 'react-native';
import { colors, spacing, typography } from '../../../theme';

export const styles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: spacing.md,
    backgroundColor: colors.black,
  },
  backButton: {
    padding: spacing.sm,
  },
  iconWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 20,
    height: 20,
  },
  headerTitle: {
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.bold,
    color: colors.white,
  },
  editButton: {
    padding: spacing.sm,
  },
  placeholder: {
    width: spacing.xxl + spacing.sm,
  },
  settingsHeaderButton: {
    padding: spacing.sm,
  },
  content: {
    flex: 1,
    paddingVertical: spacing.md,
    paddingBottom: 150, // Add more bottom padding for NavBar and extra scrolling space
  },
  
  // Profile Card
  profileCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white5,
    borderRadius: 16,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    marginBottom: spacing.md,
  },
  profileAvatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: colors.white10,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
  },
  avatarImage: {
    width: 60,
    height: 60,
    borderRadius: 30,
  },
  avatarFallback: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: colors.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarFallbackText: {
    fontSize: typography.fontSize.xl,
    fontWeight: typography.fontWeight.bold,
    color: colors.black,
  },
  avatarLoadingContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.white10,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileInfo: {
    flex: 1,
  },
  profileName: {
    fontSize: 20,
    fontWeight: typography.fontWeight.semibold,
    color: colors.white,
    marginBottom: 8,
  },
  profileId: {
    fontSize: typography.fontSize.sm,
    color: colors.white70,
    marginBottom: 4,
  },
  pointsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  pointsLabel: {
    fontSize: typography.fontSize.sm,
    color: colors.white70,
    marginRight: 4,
  },
  pointsValue: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.semibold,
    color: colors.green,
  },
  editIcon: {
    width: 30,
    height: 30,
    tintColor: colors.white,
    objectFit: 'contain',
  },
  menuIcon: {
    width: 20,
    height: 20,
    tintColor: colors.white,
    objectFit: 'contain',
  },
  chevronIcon: {
    width: 16,
    height: 16,
    tintColor: colors.white70,
    objectFit: 'contain',
  },
  
  // Menu Items
  menuItemsContainer: {
    backgroundColor: colors.white5,
    borderRadius: 16,
    paddingVertical: 8,


  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 20,
    marginVertical: 2,
  },
  menuItemText: {
    flex: 1,
    fontSize: typography.fontSize.md,
    color: colors.white,
    marginLeft: spacing.md,
    fontWeight: typography.fontWeight.medium,
  },
  logoutText: {
    color: colors.white,
  },

  
  // Section Titles
  sectionTitle: {
    fontSize: 18,
    color: colors.white,
    marginTop: 20,
    marginBottom: 15,
    fontWeight: typography.fontWeight.medium,
  },
  
  // Legacy styles (keeping for compatibility)
  profileSection: {
    alignItems: 'center',
    marginBottom: spacing.xl,
    backgroundColor: colors.black,
    borderRadius: spacing.itemSpacing,
    padding: spacing.xl,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.white,
  },
  avatarContainer: {
    width: spacing.xxl + spacing.xxxl,
    height: spacing.xxl + spacing.xxxl,
    borderRadius: spacing.xxl + spacing.screenPadding,
    marginBottom: spacing.md,
    backgroundColor: colors.green,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  avatarText: {
    fontSize: typography.fontSize.display,
    fontWeight: typography.fontWeight.bold,
    color: colors.black,
  },
  editIconContainer: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: colors.green,
    borderRadius: spacing.itemSpacing,
    width: spacing.iconSize,
    height: spacing.iconSize,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: spacing.xs / 2,
    borderColor: colors.black,
  },
  avatarLoadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.blackOverlay,
    borderRadius: spacing.xxl + spacing.screenPadding,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarLoadingText: {
    color: colors.white,
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.bold,
  },
  name: {
    fontSize: typography.fontSize.xl,
    fontWeight: typography.fontWeight.bold,
    color: colors.white,
    marginBottom: spacing.xs / 2,
  },
  email: {
    fontSize: typography.fontSize.md,
    color: colors.white70,
    marginBottom: spacing.sm,
  },
  authMethod: {
    fontSize: typography.fontSize.sm,
    color: colors.white70,
    marginTop: spacing.sm,
  },
  walletContainer: {
    alignItems: 'center',
    marginTop: spacing.sm,
  },
  walletLabel: {
    fontSize: typography.fontSize.sm,
    color: colors.white70,
    marginBottom: spacing.xs,
  },
  walletAddress: {
    fontSize: typography.fontSize.sm,
    color: colors.green,
    fontFamily: 'monospace',
  },
  settingsSectionTitle: {
    fontSize: typography.fontSize.md,
    color: colors.green,
    fontWeight: typography.fontWeight.bold,
    marginBottom: spacing.sm,
    marginTop: spacing.md,
  },
  walletSection: {
    backgroundColor: colors.black,
    borderRadius: spacing.itemSpacing,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.white,
  },
  walletHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  walletStatus: {
    fontSize: typography.fontSize.md,
    color: colors.white,
    marginLeft: spacing.sm,
    fontWeight: typography.fontWeight.medium,
  },
  connectedDot: {
    width: spacing.bellDotSize,
    height: spacing.bellDotSize,
    borderRadius: spacing.bellDotRadius,
    backgroundColor: colors.green,
    marginLeft: spacing.sm,
  },
  disconnectedDot: {
    width: spacing.bellDotSize,
    height: spacing.bellDotSize,
    borderRadius: spacing.bellDotRadius,
    backgroundColor: colors.white70,
    marginLeft: spacing.sm,
  },
  walletDetails: {
    marginBottom: spacing.md,
  },
  walletRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  walletValue: {
    fontSize: typography.fontSize.sm,
    color: colors.white,
    fontWeight: typography.fontWeight.medium,
  },
  matchedText: {
    color: colors.green,
  },
  unmatchedText: {
    color: colors.red,
  },
  walletActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  walletActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.black,
    borderRadius: spacing.sm,
    padding: spacing.sm,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.green,
    flex: 1,
    marginHorizontal: spacing.xs,
  },
  walletActionText: {
    fontSize: typography.fontSize.sm,
    color: colors.green,
    marginLeft: spacing.xs,
    fontWeight: typography.fontWeight.medium,
  },
  disconnectBtn: {
    borderColor: colors.red,
  },
  disconnectText: {
    color: colors.red,
  },
  walletMessage: {
    fontSize: typography.fontSize.sm,
    color: colors.white70,
    textAlign: 'center',
    marginBottom: spacing.md,
  },
  connectWalletBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.green,
    borderRadius: spacing.sm,
    padding: spacing.md,
  },
  connectWalletText: {
    fontSize: typography.fontSize.md,
    color: colors.black,
    fontWeight: typography.fontWeight.medium,
    marginLeft: spacing.xs,
  },
  backToDashboardButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.green,
    borderRadius: spacing.lg,
    padding: spacing.md,
  },
  backToDashboardButtonText: {
    color: colors.black,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
    marginLeft: spacing.sm,
  },
  quickActionsSection: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: spacing.lg,
    marginBottom: spacing.lg,
  },
  quickActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.black,
    borderRadius: spacing.sm,
    padding: spacing.md,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.green,
    minWidth: 120,
    justifyContent: 'center',
  },
  quickActionText: {
    fontSize: typography.fontSize.sm,
    color: colors.green,
    marginLeft: spacing.xs,
    fontWeight: typography.fontWeight.medium,
  },
  settingsOptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.sm + spacing.xs / 2,
    paddingHorizontal: spacing.sm,
    borderBottomWidth: spacing.borderWidthThin,
    borderBottomColor: colors.white10,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.green,
    borderRadius: spacing.sm,
    marginBottom: spacing.xs,
    backgroundColor: colors.white70,
  },
  settingsOptionRowDestructive: {
    borderColor: colors.red,
  },
  settingsOptionLabel: {
    flex: 1,
    color: colors.white,
    fontSize: typography.fontSize.md,
    marginLeft: spacing.itemSpacing,
  },
  settingsOptionLabelDestructive: {
    color: colors.red,
  },
  sectionMargin: {
    marginBottom: spacing.screenPadding,
  },
  noSettingsText: {
    color: colors.white,
    textAlign: 'center',
    marginTop: spacing.xxl + spacing.sm,
    fontSize: typography.fontSize.md,
  },
  privateKeySection: {
    backgroundColor: colors.white70,
    borderRadius: spacing.sm,
    padding: spacing.md,
    marginVertical: spacing.md,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.red,
  },
  privateKeyWarning: {
    color: colors.red,
    fontWeight: typography.fontWeight.bold,
    marginBottom: spacing.sm,
    fontSize: typography.fontSize.sm,
  },
  privateKeyText: {
    color: colors.white,
    fontFamily: 'monospace',
    marginBottom: spacing.md,
    fontSize: typography.fontSize.sm,
  },
  copyPrivateKeyButton: {
    backgroundColor: colors.green,
    borderRadius: spacing.xs + spacing.xs / 2,
    padding: spacing.sm,
    alignSelf: 'flex-start',
  },
  copyPrivateKeyText: {
    color: colors.black,
    fontWeight: typography.fontWeight.bold,
    fontSize: typography.fontSize.sm,
  },
  walletManagementButton: {
    backgroundColor: colors.black,
    borderRadius: spacing.itemSpacing,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.white,
  },
  walletManagementContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  walletManagementText: {
    flex: 1,
    marginLeft: spacing.md,
  },
  walletManagementTitle: {
    fontSize: typography.fontSize.md,
    color: colors.white,
    fontWeight: typography.fontWeight.medium,
    marginBottom: spacing.xs,
  },
  walletManagementSubtitle: {
    fontSize: typography.fontSize.sm,
    color: colors.white70,
  },
}); 