import { StyleSheet } from 'react-native';
import { colors } from '../../../theme/colors';
import { spacing } from '../../../theme/spacing';
import { typography } from '../../../theme/typography';

export const styles = StyleSheet.create({
  rouletteContainer: {
    height: 280,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: spacing.xl,
    overflow: 'visible',
    position: 'relative',
    width: '100%',
  },
  triangleIndicator: {
    position: 'absolute',
    top: 0,
    left: '50%',
    marginLeft: -10,
    width: 0,
    height: 0,
    borderLeftWidth: 10,
    borderRightWidth: 10,
    borderBottomWidth: 15,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: colors.white,
    zIndex: 100,
  },
  sliderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: spacing.lg, // Equal spacing top and bottom
  },
  rouletteCard: {
    width: 180,
    height: 220,
    marginHorizontal: spacing.sm,
    borderRadius: 12,
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: colors.white10,
    borderWidth: 4,
    borderColor: colors.white10,
  },
  selectedCard: {
    borderColor: colors.green,
    borderWidth: 3,
    transform: [{ scale: 1.05 }],
    
  },
  rouletteCardBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    borderRadius: 8,
  },
  rouletteCardContent: {
    flex: 1,
    padding: spacing.md,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  avatarContainer: {
    marginBottom: spacing.md,

  },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderColor: colors.white50,
  },
  defaultAvatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.white10,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
  },
  avatarText: {
    color: colors.white,
    fontSize: typography.fontSize.xl,
    fontWeight: '700',
    marginTop: 2,
  },
  placeholderIcon: {
    position: 'absolute',
    top: 8,
    left: 8,
    right: 8,
    bottom: 8,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.3,
  },
  placeholderText: {
    fontSize: 24,
    color: colors.white,
  },
  rouletteCardNameContainer: {
    alignItems: 'center',
    marginBottom: spacing.xs,
  },
  rouletteCardName: {
    color: colors.white,
    fontSize: typography.fontSize.lg,
    fontWeight: '600',
    textAlign: 'center',
  },
  rouletteCardHash: {
    color: colors.white80,
    fontSize: typography.fontSize.sm,
    fontWeight: '400',
    textAlign: 'center',
    opacity: 0.8,
  },
  spinningCard: {
    width: 140,
    height: 180,
    margin: spacing.sm,
    borderRadius: 12,
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: colors.white10,
    borderWidth: 2,
    borderColor: colors.white50,
  },
  selectedSpinningCard: {
    borderColor: colors.green,
    borderWidth: 3,
    shadowColor: colors.green,
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.8,
    shadowRadius: 10,
    elevation: 10,
  },
  loserIndicator: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: colors.green,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: 12,
    zIndex: 10,
  },
  loserText: {
    color: colors.black,
    fontSize: typography.fontSize.xs,
    fontWeight: '700',
  },
});
