import { StyleSheet } from 'react-native';

export const BG_COLOR = '#212121';
export const GREEN = '#A5EA15';
export const GRAY = '#A89B9B';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: BG_COLOR,
    flexDirection: 'column',
    paddingHorizontal: 0,
  },
  logoRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 60,
    marginBottom: 32,
  },
  logoIcon: {
    width: 40,
    height: 40,
    marginRight: 12,
    resizeMode: 'contain',
  },
  logoText: {
    fontSize: 32,
    fontFamily: 'Satoshi',
    fontWeight: '700',
    color: '#FFF',
    letterSpacing: 0.5,
  },
  logoSplit: {
    color: GREEN,
  },
  centerContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: '#FFF',
    marginBottom: 8,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 16,
    color: '#FFF',
    marginBottom: 32,
    textAlign: 'center',
    opacity: 0.8,
    width: '80%',
    alignSelf: 'center',
  },
  avatarBox: {
    width: 140,
    height: 140,
    borderRadius: 170,
    backgroundColor: 'rgba(165, 234, 21, 0.10)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.09)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 32,
    position: 'relative',
  },
  avatarIcon: {
    width: 64,
    height: 64,
    tintColor: '#FFF',
    opacity: 0.9,
  },
  editIconBox: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  editIcon: {
    width: 32,
    height: 32,
  },
  inputLabel: {
    color: '#FFF',
    fontSize: 16,
    alignSelf: 'flex-start',
    marginLeft: 32,
    marginBottom: 6,
  },
  input: {
    width: '90%',
    backgroundColor: '#FFF',
    borderRadius: 20,
    paddingVertical: 12,
    paddingHorizontal: 18,
    fontSize: 16,
    color: '#222',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: GREEN,
  },
  error: {
    color: '#FF4D4F',
    fontSize: 15,
    alignSelf: 'flex-start',
    marginLeft: 32,
    marginBottom: 8,
  },
  nextButton: {
    backgroundColor: GREEN,
    borderRadius: 20,
    paddingVertical: 14,
    width: '90%',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 0,
  },
  nextButtonText: {
    color: BG_COLOR,
    fontSize: 20,
    fontWeight: '400',
  },
  helpLink: {
    alignSelf: 'center',
    marginBottom: 32,
    textAlign: 'center',
  },
  helpText: {
    color: GRAY,
    fontSize: 16,
    opacity: 0.7,
  },
}); 