import { StyleSheet } from 'react-native';

export const BG_COLOR = '#212121';
export const GREEN = '#A5EA15';
export const GRAY = '#A89B9B';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: BG_COLOR,
    paddingHorizontal: 0,
    paddingTop: 0,
  },
  statusBar: {
    height: 44,
    backgroundColor: BG_COLOR,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 24,
    marginBottom: 12,
  },
  welcomeText: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: '400',
    marginBottom: 2,
  },
  userName: {
    color: '#FFF',
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 0,
  },
  bellContainer: {
    position: 'relative',
    padding: 8,
  },
  bellIcon: {
    width: 24,
    height: 24,
    tintColor: '#FFF',
  },
  bellDot: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: GREEN,
    borderWidth: 1,
    borderColor: '#FFF',
  },
  balanceCard: {
    backgroundColor: GREEN,
    borderRadius: 20,
    marginHorizontal: 24,
    marginTop: 8,
    padding: 20,
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  balanceLabel: {
    color: BG_COLOR,
    fontSize: 16,
    fontWeight: '500',
    marginBottom: 8,
  },
  balanceAmount: {
    color: BG_COLOR,
    fontSize: 32,
    fontWeight: 'bold',
  },
  priceLoadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  priceLoadingText: {
    color: BG_COLOR,
    fontSize: 14,
    fontWeight: '500',
    marginLeft: 8,
  },
  actionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 24,
    marginBottom: 16,
    marginTop: 0,
  },
  depositButton: {
    backgroundColor: GREEN,
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 32,
    marginRight: 12,
    alignItems: 'center',
    flex: 1,
  },
  depositText: {
    color: BG_COLOR,
    fontSize: 18,
    fontWeight: '400',
  },
  withdrawButton: {
    backgroundColor: 'transparent',
    borderColor: '#FFF',
    borderWidth: 1,
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 32,
    alignItems: 'center',
    flex: 1,
  },
  withdrawText: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: '400',
  },
  groupsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: 24,
    marginTop: 8,
    marginBottom: 8,
  },
  groupsLabel: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: '500',
  },
  addGroupText: {
    color: GREEN,
    fontSize: 16,
    fontWeight: '500',
  },
  groupsList: {
    flex: 1,
    marginHorizontal: 16,
    marginBottom: 80,
  },
  groupCard: {
    backgroundColor: BG_COLOR,
    borderRadius: 18,
    padding: 18,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#FFF',
    opacity: 1,
  },
  groupTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  groupCheckbox: {
    width: 28,
    height: 28,
    borderRadius: 7,
    borderWidth: 1.5,
    borderColor: '#D9D9D9',
    marginRight: 12,
    backgroundColor: '#E0E0E0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  groupTitle: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: 'bold',
    flex: 1,
  },
  groupDate: {
    color: GRAY,
    fontSize: 12,
    fontWeight: '400',
  },
  groupCheckboxRight: {
    width: 28,
    height: 28,
    borderRadius: 7,
    borderWidth: 1.5,
    borderColor: '#D9D9D9',
    marginLeft: 12,
    backgroundColor: '#E0E0E0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  groupDivider: {
    height: 1,
    backgroundColor: '#FFF',
    opacity: 0.7,
    marginVertical: 8,
  },
  groupCostRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    gap: 20,
    alignItems: 'center',
    marginTop: 6,
    marginBottom: 2,
  },
  groupCostLabel: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: '400',
  },
  groupCostValue: {
    color: '#FFF',
    fontSize: 15,
    fontWeight: 'bold',
  },
  groupCostValueGreen: {
    color: GREEN,
    fontSize: 15,
    fontWeight: 'bold',
  },
  groupCostValueRed: {
    color: '#FF4D4F',
    fontSize: 15,
    fontWeight: 'bold',
  },
  avatarsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#FFF',
    marginRight: -8,
    backgroundColor: '#FFF',
  },
  morePeople: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginLeft: 8,
  },
  morePeopleText: {
    color: GRAY,
    fontSize: 14,
    fontWeight: 'bold',
  },
  fabContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 24,
    alignItems: 'center',
    zIndex: 10,
  },
  fab: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: GREEN,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 6,
  },
  fabIcon: {
    color: BG_COLOR,
    fontSize: 36,
    fontWeight: 'bold',
  },
  navBarSpacer: {
    height: 64,
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  emptyStateText: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: '500',
    marginBottom: 8,
  },
  emptyStateSubtext: {
    color: GRAY,
    fontSize: 14,
    fontWeight: '400',
    textAlign: 'center',
  },
}); 