import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';
import { spacing } from '../theme/spacing';
import { typography } from '../theme/typography';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.black,
    borderRadius: 16,
    paddingHorizontal: spacing.screenPaddingHorizontal,
    height: spacing.inputHeight,
    marginBottom: spacing.lg,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.white50,
  },
  searchInput: {
    flex: 1,
    fontSize: typography.fontSize.md,
    color: colors.textLight,
    marginLeft: spacing.sm,
    height: '100%',
    textAlignVertical: 'center',
  },
  searchIcon: {
    width: 20,
    height: 20,
  },
  tabsContainer: {
    flexDirection: 'row',
    padding: 5,
    backgroundColor: colors.white5,
    borderRadius: 16,
    marginBottom: spacing.md,
    width: '100%',
    marginTop: spacing.md,
  },
  tab: {
    flex: 1,

    borderRadius: 12,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  tabActive: {
    backgroundColor: colors.green,
    shadowColor: colors.green,

  },
  tabGradient: {
    paddingHorizontal: spacing.screenPaddingHorizontal,
    paddingVertical: spacing.sm,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  tabText: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
    color: colors.white70,
  },
  tabTextActive: {
    color: colors.black,
    fontWeight: typography.fontWeight.medium,
  },
  contactsScrollView: {
    flex: 1,
  },
  animatedContentContainer: {
    flex: 1,
  },
  sectionContainer: {
    marginBottom: spacing.xl,
  },
  sectionTitle: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
    marginBottom: spacing.md,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.sm,
  },
  contactRowSelected: {
    backgroundColor: colors.white5,
    borderRadius: 12,
  },
  avatar: {
    width: spacing.xxl + spacing.sm,
    height: spacing.xxl + spacing.sm,
    borderRadius: spacing.xxl,
    backgroundColor: colors.white10,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
  },
  avatarText: {
    color: colors.white70,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.bold,
  },
  contactInfo: {
    flex: 1,
  },
  contactName: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
    marginBottom: spacing.xs / 2,
  },
  contactEmail: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
  },
  mutualGroupsText: {
    color: colors.greenBlue,
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.medium,
  },
  favoriteButton: {
    padding: spacing.sm,
  },
  selectIndicator: {
    marginLeft: spacing.sm,
  },
  checkmark: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addButton: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colors.white10,
    borderRadius: 16,
  },
  addButtonText: {
    color: colors.white,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
  },
  addButtonIcon: {
    width: 16,
    height: 16,
    resizeMode: 'contain',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: spacing.xl,
  },
  loadingText: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: spacing.xl,
  },
  searchIconEmpty: {
    height: 100,
    marginBottom: spacing.md,
    objectFit: 'contain',
  },
  emptyText: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.md,
    textAlign: 'center',
    marginTop: spacing.md,
    fontWeight: typography.fontWeight.medium,
  },
  // Toggle Contact List / Scan QR Code
  containerToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    borderBottomWidth: 2,
    borderBottomColor: colors.white50,
  },
  toggleButton: {
    flex: 1,
    alignItems: 'center',
  },
  toggleText: {
    fontSize: 18,
    fontWeight: 'normal',
    color: colors.textSecondary,
    paddingBottom: 10,
    marginBottom: -2,
    width: '100%',
    textAlign: 'center',
  },
  toggleTextActive: {
    color: colors.white,
    borderBottomWidth: 2,
    borderBottomColor: colors.green,
  },
  toggleUnderline: {
    height: 3,
    backgroundColor: colors.brandGreen,
    marginTop: 4,
    borderRadius: 2,
    width: '60%',
  },
  scrollViewContent: {
    paddingBottom: spacing.bottomNavSpace,
  },
  searchContactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  qrScannerPlaceholder: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    height: 300,
    backgroundColor: colors.darkBackground,
    borderRadius: 16,
    margin: spacing.screenPaddingHorizontal,
  },
  qrScannerPlaceholderText: {
    color: colors.textLight,
    fontSize: 18,
  },
  // QR Scanner Styles
  qrScannerContainer: {
    flex: 1,
    backgroundColor: colors.darkBackground,
  },
  permissionButton: {
    backgroundColor: colors.greenBlue,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderRadius: spacing.sm,
    marginTop: spacing.md,
  },
  permissionButtonText: {
    color: colors.white,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
    textAlign: 'center',
  },
  scannerContainer: {
    flex: 1,
    position: 'relative',
  },
  scanner: {
    flex: 1,
  },
  scannerOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  scannerOverlayText: {
    color: colors.white,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.medium,
    textAlign: 'center',
    marginBottom: spacing.lg,
  },
  scanAgainButton: {
    backgroundColor: colors.greenBlue,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderRadius: spacing.sm,
  },
  scanAgainButtonText: {
    color: colors.white,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
  },
  scannerInstructions: {
    position: 'absolute',
    bottom: spacing.xl,
    left: spacing.screenPaddingHorizontal,
    right: spacing.screenPaddingHorizontal,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    padding: spacing.md,
    borderRadius: spacing.sm,
  },
  scannerInstructionsText: {
    color: colors.white,
    fontSize: typography.fontSize.md,
    textAlign: 'center',
    fontWeight: typography.fontWeight.medium,
  },
  // Simplified QR Scanner Styles
  qrInput: {
    backgroundColor: colors.white,
    borderRadius: spacing.sm,
    padding: spacing.md,
    margin: spacing.md,
    fontSize: typography.fontSize.md,
    color: colors.textDark,
    borderWidth: 1,
    borderColor: colors.border,
  },
  scanButton: {
    backgroundColor: colors.greenBlue,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderRadius: spacing.sm,
    margin: spacing.md,
    alignItems: 'center',
  },
  scanButtonText: {
    color: colors.white,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
  },
  openCameraButton: {
    backgroundColor: colors.textSecondary,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderRadius: spacing.sm,
    margin: spacing.md,
    alignItems: 'center',
  },
  openCameraButtonText: {
    color: colors.white,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
  },
  // Camera Scanner Styles
  cameraScannerContainer: {
    flex: 1,
    position: 'relative',
  },
  cameraWebView: {
    flex: 1,
    backgroundColor: colors.darkBackground,
    height: 400,
  },
  closeCameraButton: {
    position: 'absolute',
    top: spacing.md,
    right: spacing.md,
    backgroundColor: colors.greenBlue,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: spacing.sm,
    zIndex: 1000,
  },
  closeCameraButtonText: {
    color: colors.white,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
  },
  scannerOptionsContainer: {
    alignItems: 'center',
    paddingVertical: spacing.lg,
  },
  cameraButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.brandGreen,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderRadius: spacing.sm,
    marginBottom: spacing.md,
  },
  cameraButtonText: {
    color: colors.white,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
    marginLeft: spacing.sm,
  },
  scannerDivider: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    marginVertical: spacing.md,
  },
  manualInputLabel: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
    marginBottom: spacing.sm,
  },
  // User-Friendly QR Scanner Styles
  scannerWelcomeContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.xl,
    backgroundColor: colors.darkBackground,
  },
  scannerIconContainer: {
    marginBottom: spacing.xl,
    padding: spacing.lg,
    backgroundColor: colors.white10,
    borderRadius: spacing.xl,
  },
  scannerWelcomeTitle: {
    color: colors.white,
    fontSize: typography.fontSize.xl,
    fontWeight: typography.fontWeight.bold,
    textAlign: 'center',
    marginBottom: spacing.md,
  },
  scannerWelcomeText: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    textAlign: 'center',
    marginBottom: spacing.xl,
    lineHeight: 24,
  },
  startScanButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.greenBlue,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.lg,
    borderRadius: spacing.lg,
    minWidth: 200,
    justifyContent: 'center',
  },
  startScanButtonText: {
    color: colors.white,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.bold,
    marginLeft: spacing.sm,
  },
}); 