import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';
import { spacing } from '../../theme/spacing';
import { typography } from '../../theme/typography';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.darkBackground,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.md,
    backgroundColor: colors.darkBackground,
  },
  backButton: {
    padding: spacing.sm,
  },
  headerTitle: {
    ...typography.textStyles.h3,
    color: colors.textLight,
  },
  placeholder: {
    width: spacing.xxl + spacing.sm,
  },
  content: {
    flex: 1,
    paddingHorizontal: spacing.lg,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: spacing.lg,
  },
  sectionTitle: {
    ...typography.textStyles.caption,
    color: colors.textSecondary,
    marginTop: spacing.xl,
    marginBottom: spacing.md,
    fontWeight: typography.fontWeight.medium,
  },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.lg,
    padding: spacing.md,
    marginBottom: spacing.sm,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
  },
  selectedContactRow: {
    borderColor: colors.primaryGreen,
    backgroundColor: colors.primaryGreenAlpha,
  },
  avatar: {
    width: spacing.xxl + spacing.screenPadding,
    height: spacing.xxl + spacing.screenPadding,
    borderRadius: spacing.iconSize,
    backgroundColor: colors.primaryGreen,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
  },
  avatarText: {
    color: colors.darkBackground,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.bold,
  },
  contactInfo: {
    flex: 1,
  },
  contactName: {
    ...typography.textStyles.body,
    color: colors.textLight,
    fontWeight: typography.fontWeight.medium,
  },
  contactEmail: {
    ...typography.textStyles.caption,
    color: colors.darkGray,
    marginTop: spacing.xs / 2,
  },
  amountContainer: {
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.screenPadding,
    padding: spacing.xl,
    marginVertical: spacing.lg,
    alignItems: 'center',
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
  },
  currencySymbol: {
    fontSize: spacing.iconSize,
    color: colors.darkGray,
    marginBottom: spacing.sm,
  },
  amountInput: {
    fontSize: spacing.xxl + spacing.xxxl,
    color: colors.primaryGreen,
    fontWeight: typography.fontWeight.bold,
    textAlign: 'center',
    minWidth: 200,
  },
  descriptionContainer: {
    marginVertical: spacing.lg,
  },
  descriptionLabel: {
    ...typography.textStyles.body,
    color: colors.textLight,
    marginBottom: spacing.sm,
    fontWeight: typography.fontWeight.medium,
  },
  descriptionInput: {
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.itemSpacing,
    padding: spacing.md,
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
    textAlignVertical: 'top',
  },
  confirmationCard: {
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.screenPadding,
    padding: spacing.lg,
    marginVertical: spacing.lg,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
  },
  confirmationRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  confirmationLabel: {
    ...typography.textStyles.body,
    color: colors.darkGray,
  },
  confirmationValue: {
    ...typography.textStyles.body,
    color: colors.textLight,
    fontWeight: typography.fontWeight.medium,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: spacing.md,
    borderTopWidth: spacing.borderWidthThin,
    borderTopColor: colors.textLight,
  },
  totalLabel: {
    ...typography.textStyles.h3,
    color: colors.textLight,
  },
  totalAmount: {
    ...typography.textStyles.h3,
    color: colors.primaryGreen,
  },
  successContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.lg,
  },
  successIcon: {
    width: spacing.xxl + spacing.xxxl,
    height: spacing.xxl + spacing.xxxl,
    borderRadius: spacing.xxl + spacing.screenPadding,
    backgroundColor: colors.success,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.lg,
  },
  successTitle: {
    fontSize: typography.fontSize.title,
    fontWeight: typography.fontWeight.bold,
    color: colors.textLight,
    textAlign: 'center',
    marginBottom: spacing.sm,
  },
  successMessage: {
    ...typography.textStyles.body,
    color: colors.darkGray,
    textAlign: 'center',
    marginBottom: spacing.xl,
    lineHeight: spacing.iconSize,
  },
  actionButton: {
    backgroundColor: colors.primaryGreen,
    borderRadius: spacing.lg,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    alignItems: 'center',
    marginVertical: spacing.sm,
    minWidth: '80%',
  },
  actionButtonText: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
  },
  secondaryButton: {
    backgroundColor: 'transparent',
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
    borderRadius: spacing.lg,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    alignItems: 'center',
    marginVertical: spacing.sm,
    minWidth: '80%',
  },
  secondaryButtonText: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
  },
  disabledButton: {
    backgroundColor: colors.darkGray,
    opacity: 0.6,
  },
  disabledButtonText: {
    color: colors.textSecondary,
  },
  errorText: {
    color: colors.error,
    fontSize: typography.fontSize.sm,
    textAlign: 'center',
    marginTop: spacing.sm,
  },
  balanceText: {
    ...typography.textStyles.caption,
    color: colors.darkGray,
    textAlign: 'center',
    marginTop: spacing.sm,
  },
  feesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.sm,
    paddingHorizontal: spacing.sm,
  },
  feesLabel: {
    ...typography.textStyles.caption,
    color: colors.textSecondary,
  },
  feesValue: {
    ...typography.textStyles.caption,
    color: colors.textLight,
    fontWeight: typography.fontWeight.medium,
  },
  // === MISSING STYLES FOR REQUEST CONTACTS SCREEN ===
  searchContainer: {
    marginBottom: spacing.lg,
  },
  searchInput: {
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.lg,
    padding: spacing.md,
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: spacing.xl,
  },
  loadingText: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: spacing.xl,
  },
  emptyText: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.md,
    textAlign: 'center',
  },
  contactsList: {
    flex: 1,
    marginBottom: spacing.lg,
  },
  qrCodeSection: {
    marginBottom: spacing.lg,
  },
  shareOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.lg,
    padding: spacing.md,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
    justifyContent: 'space-between',
  },
  shareOptionText: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
    flex: 1,
    marginLeft: spacing.md,
  },
  qrCodeContainer: {
    backgroundColor: colors.darkCard,
    borderRadius: spacing.lg,
    padding: spacing.lg,
    marginTop: spacing.md,
    alignItems: 'center',
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.primaryGreen,
  },
  qrCodeTitle: {
    color: colors.textLight,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.semibold,
    marginBottom: spacing.md,
    textAlign: 'center',
  },
  qrCodePlaceholder: {
    width: 200,
    height: 200,
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.lg,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.primaryGreen,
  },
  qrCodeText: {
    color: colors.primaryGreen,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
    marginTop: spacing.sm,
  },
  qrCodeLink: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.xs,
    textAlign: 'center',
    marginBottom: spacing.sm,
    fontFamily: 'monospace',
  },
  qrCodeSubtext: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.xs,
    textAlign: 'center',
    marginTop: spacing.sm,
  },
  // === MOCKUP-BASED REQUEST STYLES ===
  mockupTabsContainer: {
    flexDirection: 'row',
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.lg,
    margin: spacing.lg,
    padding: spacing.xs,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
  },
  mockupTab: {
    flex: 1,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: spacing.md,
    alignItems: 'center',
  },
  mockupTabActive: {
    backgroundColor: colors.brandGreen,
  },
  mockupTabText: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
  },
  mockupTabTextActive: {
    color: colors.darkBackground,
    fontWeight: typography.fontWeight.semibold,
  },
  mockupTabContent: {
    flex: 1,
    paddingHorizontal: spacing.lg,
  },
  mockupSearchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.lg,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
    paddingHorizontal: spacing.md,
    marginBottom: spacing.lg,
  },
  mockupSearchIcon: {
    marginRight: spacing.sm,
  },
  mockupSearchInput: {
    flex: 1,
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    paddingVertical: spacing.md,
  },
  mockupContactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.lg,
    padding: spacing.md,
    marginBottom: spacing.sm,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
  },
  mockupContactRowSelected: {
    borderColor: colors.brandGreen,
    backgroundColor: colors.darkGray,
  },
  mockupContactAvatar: {
    width: spacing.xxl,
    height: spacing.xxl,
    borderRadius: spacing.lg,
    backgroundColor: colors.brandGreen,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
  },
  mockupContactAvatarText: {
    color: colors.darkBackground,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.bold,
  },
  mockupContactInfo: {
    flex: 1,
  },
  mockupContactName: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
    marginBottom: spacing.xs / 2,
  },
  mockupContactWallet: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
  },
  mockupContactGroups: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
  },
  mockupContactsList: {
    flex: 1,
    marginBottom: spacing.lg,
  },
  mockupContactsListContent: {
    paddingBottom: spacing.lg,
  },
  mockupLoadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: spacing.xl,
  },
  mockupLoadingText: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
  },
  mockupEmptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: spacing.xl,
  },
  mockupEmptyText: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.md,
    textAlign: 'center',
  },
  mockupContinueButton: {
    backgroundColor: colors.darkGray,
    borderRadius: spacing.lg,
    paddingVertical: spacing.md,
    alignItems: 'center',
    marginBottom: spacing.lg,
  },
  mockupContinueButtonActive: {
    backgroundColor: colors.brandGreen,
  },
  mockupContinueButtonText: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
  },
  mockupContinueButtonTextActive: {
    color: colors.darkBackground,
  },
  // QR Tab Styles
  mockupQRTabContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
  },
  mockupQRTitle: {
    color: colors.textLight,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.medium,
    textAlign: 'center',
    marginBottom: spacing.xl,
  },
  mockupQRCodeContainer: {
    backgroundColor: colors.brandGreen,
    borderRadius: spacing.xl,
    padding: spacing.xl,
    alignItems: 'center',
    marginBottom: spacing.xl,
    position: 'relative',
  },
  mockupQRCode: {
    backgroundColor: colors.textLight,
    borderRadius: spacing.lg,
    padding: spacing.lg,
    marginBottom: spacing.lg,
  },
  mockupQRUserInfo: {
    alignItems: 'center',
  },
  mockupQRUserAvatar: {
    width: spacing.xxl,
    height: spacing.xxl,
    borderRadius: spacing.lg,
    backgroundColor: colors.textLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mockupQRUserAvatarText: {
    color: colors.brandGreen,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.bold,
  },
  mockupQRContinueButton: {
    backgroundColor: colors.brandGreen,
    borderRadius: spacing.lg,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.xl,
    minWidth: '80%',
    alignItems: 'center',
  },
  mockupQRContinueButtonText: {
    color: colors.darkBackground,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
  },
  // === MOCKUP REQUEST AMOUNT STYLES ===
  mockupRequestScrollContainer: {
    flex: 1,
  },
  mockupRequestScrollContent: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.xl,
  },
  mockupRequestRecipientContainer: {
    alignItems: 'center',
    marginTop: spacing.md,
    marginBottom: spacing.lg,
  },
  mockupRequestRecipientAvatar: {
    width: spacing.xxl + spacing.md,
    height: spacing.xxl + spacing.md,
    borderRadius: spacing.xl,
    backgroundColor: colors.brandGreen,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.sm,
  },
  mockupRequestRecipientAvatarText: {
    color: colors.darkBackground,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.bold,
  },
  mockupRequestRecipientName: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
    marginBottom: spacing.xs / 2,
  },
  mockupRequestRecipientEmail: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
  },
  mockupRequestAmountContainer: {
    alignItems: 'center',
    marginBottom: spacing.lg,
  },
  mockupRequestAmountLabel: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.md,
    marginBottom: spacing.sm,
  },
  mockupRequestAmountDisplay: {
    color: colors.textLight,
    fontSize: 48,
    fontWeight: typography.fontWeight.bold,
    textAlign: 'center',
    marginBottom: spacing.sm,
  },
  mockupRequestAddNoteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.lg,
    paddingVertical: spacing.xs,
  },
  mockupRequestAddNoteText: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    marginLeft: spacing.xs / 2,
    textDecorationLine: 'underline',
  },
  mockupRequestNoteContainer: {
    marginBottom: spacing.lg,
    paddingHorizontal: spacing.md,
  },
  mockupRequestNoteHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  mockupRequestNoteLabel: {
    color: colors.textLight,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
  },
  mockupRequestNoteCloseButton: {
    padding: spacing.xs,
  },
  mockupRequestNoteInput: {
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.md,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
    padding: spacing.md,
    color: colors.textLight,
    fontSize: typography.fontSize.sm,
    minHeight: 44,
    textAlignVertical: 'top',
  },
  mockupRequestNoteCounter: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.xs,
    textAlign: 'right',
    marginTop: spacing.xs / 2,
  },
  mockupRequestNumberPad: {
    paddingHorizontal: spacing.md,
    marginBottom: spacing.lg,
  },
  mockupRequestNumberPadRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: spacing.md,
  },
  mockupRequestNumberPadButton: {
    width: 60,
    height: 60,
    borderRadius: spacing.lg,
    backgroundColor: colors.darkBackground,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
  },
  mockupRequestNumberPadText: {
    color: colors.textLight,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.medium,
  },
  mockupRequestButton: {
    backgroundColor: colors.darkGray,
    borderRadius: spacing.lg,
    paddingVertical: spacing.md,
    alignItems: 'center',
    marginTop: spacing.lg,
  },
  mockupRequestButtonActive: {
    backgroundColor: colors.brandGreen,
  },
  mockupRequestButtonText: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
  },
  mockupRequestButtonTextActive: {
    color: colors.darkBackground,
  },
  // === MOCKUP REQUEST SUCCESS STYLES ===
  mockupRequestSuccessContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.xl,
  },
  mockupRequestSuccessIconContainer: {
    marginBottom: spacing.lg,
  },
  mockupRequestSuccessIcon: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: colors.darkBackground,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: spacing.borderWidthMedium,
    borderColor: colors.brandGreen,
  },
  mockupRequestSuccessTitle: {
    color: colors.textLight,
    fontSize: typography.fontSize.xl,
    fontWeight: typography.fontWeight.bold,
    textAlign: 'center',
    marginBottom: spacing.sm,
  },
  mockupRequestSuccessSubtitle: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.md,
    textAlign: 'center',
    marginBottom: spacing.xl,
    lineHeight: typography.lineHeight.relaxed,
  },
  mockupRequestSuccessCard: {
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.lg,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    width: '100%',
  },
  mockupRequestSuccessRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  mockupRequestSuccessLabel: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
  },
  mockupRequestSuccessValue: {
    color: colors.textLight,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
    flex: 1,
    textAlign: 'right',
    marginLeft: spacing.md,
  },
  mockupRequestSuccessAmount: {
    color: colors.textLight,
    fontSize: 42,
    fontWeight: typography.fontWeight.bold,
    textAlign: 'center',
    marginBottom: spacing.xl,
  },
  mockupRequestSuccessButton: {
    backgroundColor: colors.brandGreen,
    borderRadius: spacing.lg,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.xl,
    minWidth: '80%',
    alignItems: 'center',
  },
  mockupRequestSuccessButtonText: {
    color: colors.darkBackground,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
  },
  // === SEND-STYLE CONTACT STYLES FOR REQUEST ===
  sendTabsContainer: {
    flexDirection: 'row',
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.lg,
    margin: spacing.lg,
    padding: spacing.xs,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
  },
  sendTab: {
    flex: 1,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: spacing.md,
    alignItems: 'center',
  },
  sendTabActive: {
    backgroundColor: colors.brandGreen,
  },
  sendTabText: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
  },
  sendTabTextActive: {
    color: colors.darkBackground,
    fontWeight: typography.fontWeight.semibold,
  },
  sendTabContentContainer: {
    flex: 1,
  },
  sendTabContent: {
    flex: 1,
    paddingHorizontal: spacing.lg,
  },
  sendQRTabContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: spacing.xl,
  },
  sendSearchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.lg,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
    paddingHorizontal: spacing.md,
    marginBottom: spacing.lg,
  },
  sendSearchIcon: {
    marginRight: spacing.sm,
  },
  sendSearchInput: {
    flex: 1,
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    paddingVertical: spacing.md,
  },
  sendQROption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.lg,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
    padding: spacing.md,
    marginBottom: spacing.lg,
  },
  sendQROptionText: {
    flex: 1,
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    marginLeft: spacing.sm,
  },
  sendQRCodeContainer: {
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.lg,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    alignItems: 'center',
  },
  sendQRCodeTitle: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
    marginBottom: spacing.lg,
    textAlign: 'center',
  },
  sendQRCodeDisplay: {
    backgroundColor: colors.brandGreen,
    borderRadius: spacing.lg,
    padding: spacing.lg,
    alignItems: 'center',
    position: 'relative',
    marginBottom: spacing.lg,
  },
  sendQRCodeBox: {
    backgroundColor: colors.textLight,
    borderRadius: spacing.md,
    padding: spacing.lg,
  },
  sendQRUserBadge: {
    position: 'absolute',
    bottom: -spacing.sm,
    width: spacing.xl,
    height: spacing.xl,
    borderRadius: spacing.md,
    backgroundColor: colors.textLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendQRUserBadgeText: {
    color: colors.brandGreen,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.bold,
  },
  sendQRContinueButton: {
    backgroundColor: colors.brandGreen,
    borderRadius: spacing.lg,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.xl,
    alignItems: 'center',
  },
  sendQRContinueButtonText: {
    color: colors.darkBackground,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
  },
  sendQRErrorContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 120,
    height: 120,
  },
  sendQRErrorText: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    textAlign: 'center',
    marginTop: spacing.sm,
  },
  sendQRUserInfo: {
    alignItems: 'center',
    marginVertical: spacing.lg,
  },
  sendQRUserName: {
    color: colors.textLight,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.semibold,
    marginBottom: spacing.xs,
  },
  sendQRUserWallet: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
  },
  sendQRContinueButtonDisabled: {
    backgroundColor: colors.darkGray,
    opacity: 0.5,
  },
  sendQRContinueButtonTextDisabled: {
    color: colors.textSecondary,
  },
  sendContactsSection: {
    marginBottom: spacing.lg,
  },
  sendContactsSectionTitle: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
    marginBottom: spacing.md,
    marginLeft: spacing.sm,
  },
  sendContactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.lg,
    padding: spacing.md,
    marginBottom: spacing.sm,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
  },
  sendContactRowSelected: {
    borderColor: colors.brandGreen,
    backgroundColor: colors.darkGray,
  },
  sendContactAvatar: {
    width: spacing.xxl,
    height: spacing.xxl,
    borderRadius: spacing.lg,
    backgroundColor: colors.brandGreen,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
  },
  sendContactAvatarText: {
    color: colors.darkBackground,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.bold,
  },
  sendContactInfo: {
    flex: 1,
  },
  sendContactName: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
    marginBottom: spacing.xs / 2,
  },
  sendContactWallet: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
  },
  sendContactGroups: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
  },
  sendContactStar: {
    padding: spacing.sm,
    marginRight: spacing.sm,
  },
  sendContactCheck: {
    marginLeft: spacing.sm,
  },
  sendLoadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: spacing.xl,
  },
  sendLoadingText: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
  },
  sendEmptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: spacing.xl,
  },
  sendEmptyText: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.md,
    textAlign: 'center',
    marginTop: spacing.md,
  },
  sendEmptySubtext: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    textAlign: 'center',
    marginTop: spacing.sm,
    opacity: 0.7,
  },
  sendContinueButton: {
    backgroundColor: colors.darkGray,
    borderRadius: spacing.lg,
    paddingVertical: spacing.md,
    alignItems: 'center',
    margin: spacing.lg,
  },
  sendContinueButtonActive: {
    backgroundColor: colors.brandGreen,
  },
  sendContinueButtonText: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
  },
  sendContinueButtonTextActive: {
    color: colors.darkBackground,
  },
}); 