import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';
import { spacing } from '../../theme/spacing';
import { typography } from '../../theme/typography';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.darkBackground,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.md,
    backgroundColor: colors.darkBackground,
  },
  backButton: {
    padding: spacing.sm,
  },
  headerTitle: {
    ...typography.textStyles.h6,
    color: colors.white,
  },
  placeholder: {
    width: spacing.xxl + spacing.sm,
  },
  content: {
    flex: 1,
    paddingHorizontal: spacing.lg,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: spacing.lg,
  },
  sectionTitle: {
    ...typography.textStyles.caption,
    color: colors.textSecondary,
    marginTop: spacing.xl,
    marginBottom: spacing.md,
    fontWeight: typography.fontWeight.medium,
  },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.lg,
    padding: spacing.md,
    marginBottom: spacing.sm,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
  },
  selectedContactRow: {
    borderColor: colors.brandGreen,
    backgroundColor: colors.brandGreenLight,
  },
  avatar: {
    width: spacing.xxl + spacing.screenPadding,
    height: spacing.xxl + spacing.screenPadding,
    borderRadius: spacing.iconSize,
    backgroundColor: colors.brandGreen,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
  },
  avatarText: {
    color: colors.darkBackground,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.bold,
  },
  contactInfo: {
    flex: 1,
  },
  contactName: {
    ...typography.textStyles.body,
    color: colors.textLight,
    fontWeight: typography.fontWeight.medium,
  },
  contactEmail: {
    ...typography.textStyles.caption,
    color: colors.darkGray,
    marginTop: spacing.xs / 2,
  },
  amountContainer: {
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.screenPadding,
    padding: spacing.xl,
    marginVertical: spacing.lg,
    alignItems: 'center',
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
  },
  amountSection: {
    marginVertical: spacing.xl,
  },
  amountLabel: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
    marginBottom: spacing.md,
    textAlign: 'center',
  },
  currencySymbol: {
    fontSize: spacing.iconSize,
    color: colors.darkGray,
    marginBottom: spacing.sm,
  },
  amountInput: {
    fontSize: spacing.xxl + spacing.xxxl,
    color: colors.brandGreen,
    fontWeight: typography.fontWeight.bold,
    textAlign: 'center',
    minWidth: 200,
  },
  balanceInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: spacing.md,
    paddingHorizontal: spacing.lg,
  },
  balanceText: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
  },
  maxButton: {
    color: colors.brandGreen,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.bold,
    textDecorationLine: 'underline',
  },
  descriptionContainer: {
    marginVertical: spacing.lg,
  },
  descriptionLabel: {
    color: colors.textLight,
    marginBottom: spacing.sm,
    fontWeight: typography.fontWeight.medium,
    fontSize: typography.fontSize.md,
    flexDirection: 'row',
    alignItems: 'center',
  },
  descriptionInput: {
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.itemSpacing,
    padding: spacing.md,
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
    textAlignVertical: 'top',
  },
  characterCount: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.xs,
    textAlign: 'right',
    marginTop: spacing.xs,
  },
  amountHighlight: {
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.lg,
    padding: spacing.xl,
    marginBottom: spacing.lg,
    alignItems: 'center',
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.brandGreen,
  },
  amountHighlightLabel: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    marginBottom: spacing.xs,
  },
  amountHighlightValue: {
    color: colors.brandGreen,
    fontSize: typography.fontSize.xxl,
    fontWeight: typography.fontWeight.bold,
  },
  recipientCard: {
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.lg,
    padding: spacing.md,
    marginBottom: spacing.lg,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
  },
  recipientHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  recipientHeaderText: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
    marginLeft: spacing.xs,
  },
  // Alert and notification styles
  alertContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FF6B6B',
    padding: spacing.md,
    borderRadius: spacing.sm,
    marginBottom: spacing.md,
  },
  alertText: {
    color: colors.white,
    marginLeft: spacing.sm,
    fontSize: typography.fontSize.sm,
  },
  walletAddressText: {
    fontSize: typography.fontSize.xs,
    color: colors.textSecondary,
    marginTop: spacing.xs,
  },
  centeredAmountLabel: {
    fontSize: typography.fontSize.md,
    marginBottom: spacing.sm,
  },
  largeAmountValue: {
    fontSize: typography.fontSize.hero,
    fontWeight: typography.fontWeight.bold,
  },
  settlementInfoText: {
    fontSize: typography.fontSize.sm,
    color: colors.textSecondary,
    marginTop: spacing.xs,
    textAlign: 'center',
  },
  walletFromText: {
    fontSize: typography.fontSize.xs,
    color: colors.textSecondary,
    marginTop: spacing.sm,
  },

  confirmationCard: {
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.screenPadding,
    padding: spacing.lg,
    marginVertical: spacing.lg,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
  },
  confirmationCardTitle: {
    color: colors.textLight,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.medium,
    marginBottom: spacing.md,
  },
  confirmationRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  confirmationLabel: {
    color: colors.darkGray,
    fontSize: typography.fontSize.md,
  },
  confirmationValue: {
    color: colors.textLight,
    fontWeight: typography.fontWeight.medium,
    fontSize: typography.fontSize.md,
    flex: 1,
    textAlign: 'right',
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: spacing.md,
    borderTopWidth: spacing.borderWidthThin,
    borderTopColor: colors.textLight,
  },
  totalLabel: {
    color: colors.textLight,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.medium,
  },
  totalAmount: {
    color: colors.brandGreen,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.bold,
  },
  securityNotice: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.brandGreenLight,
    borderRadius: spacing.md,
    padding: spacing.md,
    marginBottom: spacing.xl,
  },
  securityNoticeText: {
    color: colors.textLight,
    fontSize: typography.fontSize.sm,
    marginLeft: spacing.sm,
    flex: 1,
  },
  successContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.lg,
  },
  successIconContainer: {
    position: 'relative',
    marginBottom: spacing.xl,
  },
  successIcon: {
    width: spacing.xxl + spacing.xxxl,
    height: spacing.xxl + spacing.xxxl,
    borderRadius: spacing.xxl + spacing.screenPadding,
    backgroundColor: colors.brandGreen,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.brandGreen,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  successRipple: {
    position: 'absolute',
    width: spacing.xxl + spacing.xxxl + spacing.lg,
    height: spacing.xxl + spacing.xxxl + spacing.lg,
    borderRadius: spacing.xxl + spacing.screenPadding + spacing.md,
    backgroundColor: colors.brandGreen,
    opacity: 0.2,
    top: -spacing.md,
    left: -spacing.md,
  },
  successTitle: {
    fontSize: typography.fontSize.title,
    fontWeight: typography.fontWeight.bold,
    color: colors.textLight,
    textAlign: 'center',
    marginBottom: spacing.sm,
  },
  successMessage: {
    color: colors.textSecondary,
    textAlign: 'center',
    marginBottom: spacing.xl,
    lineHeight: spacing.iconSize,
    fontSize: typography.fontSize.md,
    paddingHorizontal: spacing.lg,
  },
  successRecipientCard: {
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.lg,
    padding: spacing.md,
    marginBottom: spacing.lg,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.brandGreen,
    width: '100%',
  },
  successRecipientHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  successRecipientHeaderText: {
    color: colors.brandGreen,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
    marginLeft: spacing.xs,
  },
  amountSent: {
    color: colors.brandGreen,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.bold,
  },
  transactionSummary: {
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.lg,
    padding: spacing.lg,
    marginBottom: spacing.xl,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
    width: '100%',
  },
  transactionSummaryTitle: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
    marginBottom: spacing.md,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: spacing.sm,
  },
  summaryLabel: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    flex: 1,
  },
  summaryValue: {
    color: colors.textLight,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
    flex: 2,
    textAlign: 'right',
  },
  actionButton: {
    backgroundColor: colors.brandGreen,
    borderRadius: spacing.lg,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    alignItems: 'center',
    marginVertical: spacing.sm,
    minWidth: '80%',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  actionButtonText: {
    color: colors.darkBackground,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
    marginRight: spacing.xs,
  },
  secondaryActions: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    marginTop: spacing.md,
  },
  secondaryButton: {
    backgroundColor: 'transparent',
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
    borderRadius: spacing.lg,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    alignItems: 'center',
    marginVertical: spacing.sm,
    flexDirection: 'row',
    flex: 1,
    marginHorizontal: spacing.xs,
    justifyContent: 'center',
  },
  secondaryButtonText: {
    color: colors.textLight,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
    marginLeft: spacing.xs,
  },
  disabledButton: {
    backgroundColor: colors.darkGray,
    opacity: 0.6,
  },
  disabledButtonText: {
    color: colors.textSecondary,
  },
  errorText: {
    color: colors.error,
    fontSize: typography.fontSize.sm,
    textAlign: 'center',
    marginTop: spacing.sm,
  },
  feesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.sm,
    paddingHorizontal: spacing.sm,
  },
  feesLabel: {
    ...typography.textStyles.caption,
    color: colors.textSecondary,
  },
  feesValue: {
    ...typography.textStyles.caption,
    color: colors.textLight,
    fontWeight: typography.fontWeight.medium,
  },
  // === MISSING STYLES FOR SEND CONTACTS SCREEN ===
  searchContainer: {
    marginBottom: spacing.lg,
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
  },
  searchInput: {
    flex: 1,
    fontSize: typography.fontSize.md,
    color: colors.textLight,
    marginLeft: spacing.sm,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: spacing.xl,
  },
  loadingText: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: spacing.xl,
  },
  emptyText: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.md,
    textAlign: 'center',
    marginTop: spacing.md,
    fontWeight: typography.fontWeight.medium,
  },
  emptySubtext: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    textAlign: 'center',
    marginTop: spacing.sm,
    opacity: 0.7,
  },
  contactsList: {
    flex: 1,
  },
  contactsListContent: {
    paddingBottom: spacing.lg,
  },
  // === MOCKUP-BASED SEND CONTACTS STYLES ===
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.md,
    padding: spacing.xs,
    marginBottom: spacing.lg,
    gap: 20,
  },
  tab: {
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 16,
    alignItems: 'center',
    backgroundColor: colors.white10,
  },
  activeTab: {
    backgroundColor: colors.green,
  },
  tabText: {
    color: colors.white70,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.regular,
  },
  activeTabText: {
    color: colors.black,
    fontWeight: typography.fontWeight.semibold,
  },
  mockupSearchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.black,
    borderRadius: 16,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    marginBottom: spacing.lg,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
  },
  mockupSearchInput: {
    flex: 1,
    fontSize: typography.fontSize.md,
    color: colors.textLight,
    marginLeft: spacing.sm,
  },
  contactsScrollView: {
    flex: 1,
  },
  sectionContainer: {
    marginBottom: spacing.xl,
  },
  mockupSectionTitle: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
    marginBottom: spacing.md,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  mockupContactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.sm,
  },
  mockupAvatar: {
    width: spacing.xxl + spacing.sm,
    height: spacing.xxl + spacing.sm,
    borderRadius: spacing.xxl,
    backgroundColor: colors.brandGreen,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
  },
  mockupAvatarText: {
    color: colors.darkBackground,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.bold,
  },
  mockupContactInfo: {
    flex: 1,
  },
  mockupContactName: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
    marginBottom: spacing.xs / 2,
  },
  mockupContactEmail: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
  },
  mutualGroupsText: {
    color: colors.brandGreen,
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.medium,
  },
  favoriteButton: {
    padding: spacing.sm,
  },
  // === MOCKUP-BASED SEND AMOUNT STYLES ===
  recipientAvatarContainer: {
    alignItems: 'center',
    marginTop: spacing.xl,
    marginBottom: spacing.xxl,
  },
  recipientAvatar: {
    width: spacing.xxxl + spacing.xl,
    height: spacing.xxxl + spacing.xl,
    borderRadius: spacing.xxl + spacing.lg,
    backgroundColor: colors.brandGreen,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
  },
  recipientAvatarText: {
    color: colors.darkBackground,
    fontSize: typography.fontSize.xl,
    fontWeight: typography.fontWeight.bold,
  },
  recipientName: {
    color: colors.textLight,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.medium,
    marginBottom: spacing.xs,
  },
  recipientEmail: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
  },
  amountDisplayContainer: {
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  enterAmountLabel: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    marginBottom: spacing.sm,
  },
  amountDisplay: {
    color: colors.textLight,
    fontSize: spacing.xxxl + spacing.lg,
    fontWeight: typography.fontWeight.bold,
    textAlign: 'center',
  },
  addNoteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.xl,
    paddingVertical: spacing.sm,
  },
  addNoteText: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    marginLeft: spacing.xs,
    textDecorationLine: 'underline',
  },
  noteInputContainer: {
    alignItems: 'center',
    marginBottom: spacing.xl,
    paddingHorizontal: spacing.lg,
  },
  noteLabel: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    marginBottom: spacing.xs,
  },
  noteInput: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    textAlign: 'center',
  },
  numberPad: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: spacing.xl,
    marginBottom: spacing.lg,
  },
  numberPadRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: spacing.lg,
  },
  numberPadButton: {
    width: spacing.xxxl + spacing.md,
    height: spacing.xxxl + spacing.md,
    borderRadius: spacing.xxl,
    backgroundColor: colors.darkBackground,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
  },
  numberPadText: {
    color: colors.textLight,
    fontSize: typography.fontSize.xl,
    fontWeight: typography.fontWeight.medium,
  },
  mockupContinueButton: {
    backgroundColor: colors.darkGray,
    borderRadius: spacing.lg,
    paddingVertical: spacing.md,
    marginHorizontal: spacing.lg,
    marginBottom: spacing.lg,
    alignItems: 'center',
  },
  mockupContinueButtonActive: {
    backgroundColor: colors.brandGreen,
  },
  mockupContinueButtonText: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
  },
  mockupContinueButtonTextActive: {
    color: colors.darkBackground,
  },
  // === MOCKUP-BASED SEND CONFIRMATION STYLES ===
  mockupRecipientCard: {
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.lg,
    padding: spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.xl,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
  },
  mockupRecipientAvatar: {
    width: spacing.xxl + spacing.sm,
    height: spacing.xxl + spacing.sm,
    borderRadius: spacing.xxl,
    backgroundColor: colors.brandGreen,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
  },
  mockupRecipientAvatarText: {
    color: colors.darkBackground,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.bold,
  },
  mockupRecipientInfo: {
    flex: 1,
  },
  mockupRecipientName: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
    marginBottom: spacing.xs / 2,
  },
  mockupRecipientEmail: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
  },
  sentAmountContainer: {
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  sentAmountLabel: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    marginBottom: spacing.sm,
  },
  sentAmountValue: {
    color: colors.textLight,
    fontSize: typography.fontSize.xxl,
    fontWeight: typography.fontWeight.bold,
  },
  mockupTransactionDetails: {
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.lg,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
  },
  mockupFeeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  mockupFeeLabel: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
  },
  mockupFeeValue: {
    color: colors.textLight,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
  },
  mockupTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: spacing.md,
    borderTopWidth: spacing.borderWidthThin,
    borderTopColor: colors.textLight,
  },
  mockupTotalLabel: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
  },
  mockupTotalValue: {
    color: colors.brandGreen,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.bold,
  },
  mockupNoteContainer: {
    alignItems: 'center',
    marginBottom: spacing.lg,
    paddingHorizontal: spacing.lg,
  },
  mockupNoteText: {
    color: colors.textLight,
    fontSize: typography.fontSize.sm,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  walletInfoContainer: {
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.md,
    padding: spacing.md,
    marginBottom: spacing.xl,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
  },
  walletInfoText: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    textAlign: 'center',
    lineHeight: spacing.lg,
  },
  mockupSignButton: {
    backgroundColor: colors.brandGreen,
    borderRadius: spacing.lg,
    paddingVertical: spacing.md,
    marginHorizontal: spacing.lg,
    marginBottom: spacing.lg,
    alignItems: 'center',
  },
  mockupSignButtonText: {
    color: colors.darkBackground,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
  },
  // === MOCKUP-BASED SEND SUCCESS STYLES ===
  mockupSuccessContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.lg,
  },
  mockupSuccessIcon: {
    width: spacing.xxxl + spacing.xxl,
    height: spacing.xxxl + spacing.xxl,
    borderRadius: spacing.xxxl + spacing.lg,
    backgroundColor: colors.brandGreen,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.xl,
    shadowColor: colors.brandGreen,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  mockupSuccessTitle: {
    color: colors.textLight,
    fontSize: typography.fontSize.title,
    fontWeight: typography.fontWeight.bold,
    textAlign: 'center',
    marginBottom: spacing.sm,
  },
  mockupSuccessDate: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    textAlign: 'center',
    marginBottom: spacing.xl,
  },
  mockupSentAmountContainer: {
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  mockupSentAmountLabel: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    marginBottom: spacing.sm,
  },
  mockupSentAmountValue: {
    color: colors.textLight,
    fontSize: typography.fontSize.xxl,
    fontWeight: typography.fontWeight.bold,
  },
  mockupSuccessNoteContainer: {
    alignItems: 'center',
    marginBottom: spacing.xxxl,
    paddingHorizontal: spacing.lg,
  },
  mockupSuccessNoteText: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  mockupBackHomeButton: {
    backgroundColor: colors.brandGreen,
    borderRadius: spacing.lg,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.xl,
    minWidth: '80%',
    alignItems: 'center',
  },
  mockupBackHomeButtonText: {
    color: colors.darkBackground,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
  },
  // === SEND TABS STYLES ===
  sendTabsContainer: {
    flexDirection: 'row',
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.lg,
    margin: spacing.lg,
    padding: spacing.xs,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
  },
  sendTab: {
    flex: 1,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: spacing.md,
    alignItems: 'center',
  },
  sendTabActive: {
    backgroundColor: colors.brandGreen,
  },
  sendTabText: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
  },
  sendTabTextActive: {
    color: colors.darkBackground,
    fontWeight: typography.fontWeight.semibold,
  },
  // === SEND QR CODE STYLES ===
  sendQRTabContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: spacing.xl,
  },
  sendQRCodeTitle: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
    marginBottom: spacing.lg,
    textAlign: 'center',
  },
  sendQRCodeDisplay: {
    backgroundColor: colors.brandGreen,
    borderRadius: spacing.lg,
    padding: spacing.lg,
    alignItems: 'center',
    position: 'relative',
    marginBottom: spacing.lg,
  },
  sendQRCodeBox: {
    backgroundColor: colors.textLight,
    borderRadius: spacing.md,
    padding: spacing.lg,
  },
  sendQRUserBadge: {
    position: 'absolute',
    bottom: -spacing.sm,
    width: spacing.xl,
    height: spacing.xl,
    borderRadius: spacing.md,
    backgroundColor: colors.textLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendQRUserBadgeText: {
    color: colors.brandGreen,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.bold,
  },
  sendQRContinueButton: {
    backgroundColor: colors.brandGreen,
    borderRadius: spacing.lg,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.xl,
    alignItems: 'center',
  },
  sendQRContinueButtonText: {
    color: colors.darkBackground,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
  },

}); 