import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';
import { spacing } from '../../theme/spacing';
import { typography } from '../../theme/typography';

export const styles = StyleSheet.create({
  content: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: spacing.lg,
  },
  sectionTitle: {
    ...typography.textStyles.caption,
    color: colors.textSecondary,
    marginTop: spacing.xl,
    marginBottom: spacing.md,
    fontWeight: typography.fontWeight.medium,
  },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.lg,
    padding: spacing.md,
    marginBottom: spacing.sm,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
  },
  selectedContactRow: {
    borderColor: colors.brandGreen,
    backgroundColor: colors.brandGreenLight,
  },
  avatar: {
    width: spacing.xxl + spacing.screenPadding,
    height: spacing.xxl + spacing.screenPadding,
    borderRadius: spacing.iconSize,
    backgroundColor: colors.green,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
  },
  avatarText: {
    color: colors.black,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.bold,
  },
  contactInfo: {
    flex: 1,
  },
  contactName: {
    ...typography.textStyles.body,
    color: colors.textLight,
    fontWeight: typography.fontWeight.medium,
  },
  contactEmail: {
    ...typography.textStyles.caption,
    color: colors.darkGray,
    marginTop: spacing.xs / 2,
  },
  amountContainer: {
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.screenPadding,
    padding: spacing.xl,
    marginVertical: spacing.lg,
    alignItems: 'center',
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
  },
  amountSection: {
    marginVertical: spacing.xl,
  },
  amountLabel: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
    marginBottom: spacing.md,
    textAlign: 'center',
  },
  currencySymbol: {
    fontSize: spacing.iconSize,
    color: colors.darkGray,
    marginBottom: spacing.sm,
  },
  amountInput: {
    fontSize: spacing.xxl + spacing.xxxl,
    color: colors.brandGreen,
    fontWeight: typography.fontWeight.bold,
    textAlign: 'center',
    minWidth: 200,
  },
  balanceInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: spacing.md,
  },
  balanceText: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
  },
  maxButton: {
    color: colors.brandGreen,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.bold,
    textDecorationLine: 'underline',
  },
  descriptionContainer: {
    marginVertical: spacing.lg,
  },
  descriptionLabel: {
    color: colors.textLight,
    marginBottom: spacing.sm,
    fontWeight: typography.fontWeight.medium,
    fontSize: typography.fontSize.md,
    flexDirection: 'row',
    alignItems: 'center',
  },
  descriptionInput: {
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.itemSpacing,
    padding: spacing.md,
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
    textAlignVertical: 'top',
  },
  characterCount: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.xs,
    textAlign: 'right',
    marginTop: spacing.xs,
  },
  amountHighlight: {
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.lg,
    padding: spacing.xl,
    marginBottom: spacing.lg,
    alignItems: 'center',
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.brandGreen,
  },
  amountHighlightLabel: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    marginBottom: spacing.xs,
  },
  amountHighlightValue: {
    color: colors.brandGreen,
    fontSize: typography.fontSize.xxl,
    fontWeight: typography.fontWeight.bold,
  },
  recipientCard: {
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.lg,
    padding: spacing.md,
    marginBottom: spacing.lg,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
  },
  recipientHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  recipientHeaderText: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
    marginLeft: spacing.xs,
  },
  // Alert and notification styles
  alertContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FF6B6B',
    padding: spacing.md,
    borderRadius: spacing.sm,
    marginBottom: spacing.md,
  },
  alertText: {
    color: colors.white,
    marginLeft: spacing.sm,
    fontSize: typography.fontSize.sm,
  },
  walletAddressText: {
    fontSize: typography.fontSize.xs,
    color: colors.textSecondary,
    marginTop: spacing.xs,
  },
  centeredAmountLabel: {
    fontSize: typography.fontSize.md,
    marginBottom: spacing.sm,
  },
  largeAmountValue: {
    fontSize: typography.fontSize.hero,
    fontWeight: typography.fontWeight.bold,
  },
  settlementInfoText: {
    fontSize: typography.fontSize.sm,
    color: colors.textSecondary,
    marginTop: spacing.xs,
    textAlign: 'center',
  },
  walletFromText: {
    fontSize: typography.fontSize.xs,
    color: colors.textSecondary,
    marginTop: spacing.sm,
  },

  confirmationCard: {
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.screenPadding,
    padding: spacing.lg,
    marginVertical: spacing.lg,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
  },
  confirmationCardTitle: {
    color: colors.textLight,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.medium,
    marginBottom: spacing.md,
  },
  confirmationRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  confirmationLabel: {
    color: colors.darkGray,
    fontSize: typography.fontSize.md,
  },
  confirmationValue: {
    color: colors.textLight,
    fontWeight: typography.fontWeight.medium,
    fontSize: typography.fontSize.md,
    flex: 1,
    textAlign: 'right',
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: spacing.md,
    borderTopWidth: spacing.borderWidthThin,
    borderTopColor: colors.textLight,
  },
  totalLabel: {
    color: colors.textLight,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.medium,
  },
  totalAmount: {
    color: colors.brandGreen,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.bold,
  },
  securityNotice: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.brandGreenLight,
    borderRadius: spacing.md,
    padding: spacing.md,
    marginBottom: spacing.xl,
  },
  securityNoticeText: {
    color: colors.textLight,
    fontSize: typography.fontSize.sm,
    marginLeft: spacing.sm,
    flex: 1,
  },
  successContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.lg,
  },
  successIconContainer: {
    position: 'relative',
    marginBottom: spacing.xl,
  },
  successIcon: {
    width: spacing.xxl + spacing.xxxl,
    height: spacing.xxl + spacing.xxxl,
    borderRadius: spacing.xxl + spacing.screenPadding,
    backgroundColor: colors.brandGreen,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.brandGreen,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  successRipple: {
    position: 'absolute',
    width: spacing.xxl + spacing.xxxl + spacing.lg,
    height: spacing.xxl + spacing.xxxl + spacing.lg,
    borderRadius: spacing.xxl + spacing.screenPadding + spacing.md,
    backgroundColor: colors.brandGreen,
    opacity: 0.2,
    top: -spacing.md,
    left: -spacing.md,
  },
  successTitle: {
    fontSize: typography.fontSize.title,
    fontWeight: typography.fontWeight.bold,
    color: colors.textLight,
    textAlign: 'center',
    marginBottom: spacing.sm,
  },
  successMessage: {
    color: colors.textSecondary,
    textAlign: 'center',
    marginBottom: spacing.xl,
    lineHeight: spacing.iconSize,
    fontSize: typography.fontSize.md,
    paddingHorizontal: spacing.screenPaddingHorizontal,
  },
  successRecipientCard: {
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.lg,
    padding: spacing.md,
    marginBottom: spacing.lg,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.brandGreen,
    width: '100%',
  },
  successRecipientHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  successRecipientHeaderText: {
    color: colors.brandGreen,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
    marginLeft: spacing.xs,
  },
  amountSent: {
    color: colors.brandGreen,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.bold,
  },
  transactionSummary: {
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.lg,
    padding: spacing.lg,
    marginBottom: spacing.xl,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
    width: '100%',
  },
  transactionSummaryTitle: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
    marginBottom: spacing.md,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: spacing.sm,
  },
  summaryLabel: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    flex: 1,
  },
  summaryValue: {
    color: colors.textLight,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
    flex: 2,
    textAlign: 'right',
  },
  actionButton: {
    backgroundColor: colors.brandGreen,
    borderRadius: spacing.lg,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.screenPaddingHorizontal,
    alignItems: 'center',
    marginVertical: spacing.sm,
    minWidth: '80%',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  actionButtonText: {
    color: colors.darkBackground,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
    marginRight: spacing.xs,
  },
  secondaryActions: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    marginTop: spacing.md,
  },
  secondaryButton: {
    backgroundColor: 'transparent',
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
    borderRadius: spacing.lg,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    alignItems: 'center',
    marginVertical: spacing.sm,
    flexDirection: 'row',
    flex: 1,
    marginHorizontal: spacing.xs,
    justifyContent: 'center',
  },
  secondaryButtonText: {
    color: colors.textLight,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
    marginLeft: spacing.xs,
  },
  disabledButton: {
    backgroundColor: colors.darkGray,
    opacity: 0.6,
  },
  disabledButtonText: {
    color: colors.textSecondary,
  },
  errorText: {
    color: colors.error,
    fontSize: typography.fontSize.sm,
    textAlign: 'center',
    marginTop: spacing.sm,
  },
  feesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.sm,
    paddingHorizontal: spacing.sm,
  },
  feesLabel: {
    ...typography.textStyles.caption,
    color: colors.textSecondary,
  },
  feesValue: {
    ...typography.textStyles.caption,
    color: colors.textLight,
    fontWeight: typography.fontWeight.medium,
  },
  // === MISSING STYLES FOR SEND CONTACTS SCREEN ===
  searchContainer: {
    marginBottom: spacing.lg,
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.lg,
    paddingHorizontal: spacing.screenPaddingHorizontal,
    height: spacing.inputHeight,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
  },
  searchInput: {
    flex: 1,
    fontSize: typography.fontSize.md,
    color: colors.textLight,
    marginLeft: spacing.sm,
    height: '100%',
    textAlignVertical: 'center',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: spacing.xl,
  },
  loadingText: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: spacing.xl,
  },
  emptyText: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.md,
    textAlign: 'center',
    marginTop: spacing.md,
    fontWeight: typography.fontWeight.medium,
  },
  emptySubtext: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    textAlign: 'center',
    marginTop: spacing.sm,
    opacity: 0.7,
  },
  contactsList: {
    flex: 1,
  },
  contactsListContent: {
    paddingBottom: spacing.lg,
  },
  // === MOCKUP-BASED SEND CONTACTS STYLES ===
  tabContainer: {
    flexDirection: 'row',
    marginHorizontal: spacing.md,
    marginBottom: spacing.lg,
    borderBottomWidth: 1,
    borderColor: colors.white50,
  },
  tab: {
    flex: 1,
    alignItems: 'center',
    marginBottom: -1,
  },
  activeTab: {
    // Gradient indicator is rendered in component
  },
  tabText: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.regular,
  },
  activeTabText: {
    color: colors.white,
    fontWeight: typography.fontWeight.semibold,
  },
  tabIndicatorContainer: {
    height: 2,
    width: '100%',
    marginTop: 10,
    borderRadius: 2,
    overflow: 'hidden',
  },
  tabIndicatorPlaceholder: {
    height: 2,
    width: '100%',
    marginTop: 6,
    borderRadius: 2,
    backgroundColor: 'transparent',
  },
  mockupSearchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.black,
    borderRadius: 16,
    paddingHorizontal: spacing.screenPaddingHorizontal,
    height: spacing.inputHeight,
    marginBottom: spacing.lg,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
  },
  mockupSearchInput: {
    flex: 1,
    fontSize: typography.fontSize.md,
    color: colors.textLight,
    marginLeft: spacing.sm,
    height: '100%',
    textAlignVertical: 'center',
  },
  contactsScrollView: {
    flex: 1,
  },
  sectionContainer: {
    marginBottom: spacing.xl,
  },
  mockupSectionTitle: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
    marginBottom: spacing.md,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  mockupContactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.sm,
  },
  mockupAvatar: {
    width: spacing.xxl + spacing.sm,
    height: spacing.xxl + spacing.sm,
    borderRadius: spacing.xxl,
    backgroundColor: colors.brandGreen,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
  },
  mockupAvatarText: {
    color: colors.darkBackground,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.bold,
  },
  mockupContactInfo: {
    flex: 1,
  },
  mockupContactName: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
    marginBottom: spacing.xs / 2,
  },
  mockupContactEmail: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
  },
  mutualGroupsText: {
    color: colors.brandGreen,
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.medium,
  },
  favoriteButton: {
    padding: spacing.sm,
  },
  // === MOCKUP-BASED SEND AMOUNT STYLES ===
  recipientAvatarContainer: {
    alignItems: 'center',
    marginTop: spacing.xxxl,
    marginBottom: spacing.xxxl,
  },
  recipientAvatar: {
    width: 70,
    height: 70,
    borderRadius: spacing.xxl + spacing.lg,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
    overflow: 'hidden',
  },
  recipientWalletIcon: {
    width: '100%',
    height: '100%',
    borderRadius: spacing.xxl,
    backgroundColor: colors.white10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recipientKastIcon: {
    width: '100%',
    height: '100%',
    borderRadius: spacing.xxl,
    alignItems: 'center',
    justifyContent: 'center',
  },

  recipientWalletIconImage: {
    width: 25,
    height: 25,
  },
  recipientAvatarTextWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
    backgroundColor: colors.brandGreen,
  },
  recipientAvatarText: {
    color: colors.black,
    fontSize: 25,
    fontWeight: typography.fontWeight.bold,
  },
  recipientName: {
    color: colors.white,
    fontSize: 20,
    fontWeight: typography.fontWeight.medium,
    marginBottom: spacing.sm,
  },
  recipientEmail: {
    color: colors.white70,
    fontSize: 14,
  },
  amountDisplayContainer: {
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  enterAmountLabel: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    marginBottom: spacing.sm,
  },
  amountDisplay: {
    color: colors.textLight,
    fontSize: spacing.xxxl + spacing.lg,
    fontWeight: typography.fontWeight.bold,
    textAlign: 'center',
  },
  addNoteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.xl,
    paddingVertical: spacing.sm,
  },
  addNoteText: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    marginLeft: spacing.xs,
    textDecorationLine: 'underline',
  },
  noteInputContainer: {
    alignItems: 'center',
    marginBottom: spacing.xl,
    paddingHorizontal: spacing.lg,
  },
  noteLabel: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    marginBottom: spacing.xs,
  },
  noteInput: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    textAlign: 'center',
  },
  numberPad: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: spacing.screenPaddingHorizontal,
    marginBottom: spacing.lg,
  },
  numberPadRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: spacing.lg,
  },
  numberPadButton: {
    width: spacing.xxxl + spacing.md,
    height: spacing.xxxl + spacing.md,
    borderRadius: spacing.xxl,
    backgroundColor: colors.darkBackground,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
  },
  numberPadText: {
    color: colors.textLight,
    fontSize: typography.fontSize.xl,
    fontWeight: typography.fontWeight.medium,
  },
  mockupContinueButton: {
    marginBottom: spacing.md,
    width: '100%',
  },
  mockupContinueButtonActive: {
    backgroundColor: colors.brandGreen,
  },
  mockupContinueButtonText: {
    color: colors.white50,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
  },
  mockupContinueButtonTextActive: {
    color: colors.black,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
  },
  // === MOCKUP-BASED SEND CONFIRMATION STYLES ===
  mockupRecipientCard: {
    backgroundColor: colors.white5,
    borderRadius: spacing.lg,
    paddingHorizontal: spacing.screenPaddingHorizontal,
    paddingVertical: 15,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.lg,
    marginTop: spacing.lg,
  },
  mockupRecipientAvatar: {
    width: spacing.xxl + spacing.sm,
    height: spacing.xxl + spacing.sm,
    borderRadius: spacing.xxl,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
    overflow: 'hidden',
  },
  mockupRecipientAvatarTextWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
    backgroundColor: colors.brandGreen,
  },
  mockupRecipientAvatarText: {
    color: colors.darkBackground,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.bold,
    
  },
  mockupRecipientInfo: {
    flex: 1,
  },
  mockupRecipientName: {
    color: colors.white,
    fontSize: 16,
    fontWeight: typography.fontWeight.medium,
    marginBottom: spacing.xs,
  },
  mockupRecipientEmail: {
    color: colors.white70,
    fontSize: 14,
  },
  sentAmountContainer: {
    alignItems: 'flex-start',
    marginBottom: spacing.lg,
    backgroundColor: colors.white5,
    borderRadius: spacing.lg,
    padding: spacing.lg,
    width: '100%',
  },
  sentAmountValueContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginBottom: spacing.md,
    width: '100%',
  },
  sentAmountLabel: {
    color: colors.white,
    fontSize: typography.fontSize.md,
    marginBottom: spacing.md,
  },
  sentAmountValue: {
    color: colors.white,
    fontSize: 40,
    fontWeight: typography.fontWeight.bold,
  },
  mockupTransactionDetails: {
    backgroundColor: colors.white5,
    borderRadius: spacing.lg,
    padding: spacing.lg,
    width: '100%',
  },
  mockupFeeRowSeparator: {
    height: 0.5,
    backgroundColor: colors.white50,
    marginBottom: spacing.md,
  },
  mockupFeeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  mockupFeeLabel: {
    color: colors.white70,
    fontSize: 14,
  },
  mockupFeeValue: {
    color: colors.white,
    fontSize: 16,
    fontWeight: typography.fontWeight.medium,
  },
  mockupTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: spacing.md,
    borderTopWidth: spacing.borderWidthThin,
    borderTopColor: colors.textLight,
  },
  mockupTotalLabel: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
  },
  mockupTotalValue: {
    color: colors.brandGreen,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.bold,
  },
  mockupNoteContainer: {
    justifyContent: 'flex-start',
    borderTopWidth: 0.5,
    borderTopColor: colors.white50,
    paddingTop: spacing.md,
    width: '100%',



  },
  mockupNoteText: {
    color: colors.white,
    fontSize: 16,
    textAlign: 'left',
    width: '95%',
  },
  walletInfoContainer: {
    backgroundColor: colors.darkBackground,
    borderRadius: spacing.md,
    padding: spacing.md,
    marginBottom: spacing.xl,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.textLight,
  },
  walletInfoText: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    textAlign: 'center',
    lineHeight: spacing.lg,
  },
  mockupSignButton: {
    backgroundColor: colors.brandGreen,
    borderRadius: spacing.lg,
    paddingVertical: spacing.md,
    marginHorizontal: spacing.lg,
    marginBottom: spacing.lg,
    alignItems: 'center',
  },
  mockupSignButtonText: {
    color: colors.darkBackground,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
  },
  // === MOCKUP-BASED SEND SUCCESS STYLES ===
  mockupSuccessContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.lg,
  },
  mockupSuccessIcon: {
    width: 200,
    height: 200,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
  },
  mockupSuccessIconImage: {
    height: 200,
    width: 200,
    objectFit: 'contain',
  },
  mockupSuccessTitle: {
    color: colors.white,
    fontSize: 24,
    fontWeight: typography.fontWeight.semibold,
    textAlign: 'center',
    marginBottom: spacing.sm,
  },
  mockupSuccessDescription: {
    color: colors.white70,
    fontSize: 16,
    fontWeight: typography.fontWeight.medium,
    textAlign: 'center',
    marginBottom: 100,
  },
  mockupSuccessDate: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    textAlign: 'center',
    marginBottom: spacing.xl,
  },
  mockupSentAmountContainer: {
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  mockupSentAmountLabel: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    marginBottom: spacing.sm,
  },
  mockupSentAmountValue: {
    color: colors.textLight,
    fontSize: typography.fontSize.xxl,
    fontWeight: typography.fontWeight.bold,
  },
  mockupSuccessNoteContainer: {
    alignItems: 'center',
    marginBottom: spacing.xxxl,
    paddingHorizontal: spacing.screenPaddingHorizontal,
  },
  mockupSuccessNoteText: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  mockupBackHomeButton: {
    width: '100%',
    marginBottom: spacing.md,
  },

  // === SEND QR CODE STYLES ===
  sendQRTabContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: spacing.xl,
  },
  sendQRCodeTitle: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
    marginBottom: spacing.lg,
    textAlign: 'center',
  },
  sendQRCodeDisplay: {
    backgroundColor: colors.brandGreen,
    borderRadius: spacing.lg,
    padding: spacing.lg,
    alignItems: 'center',
    position: 'relative',
    marginBottom: spacing.lg,
  },
  sendQRCodeBox: {
    backgroundColor: colors.textLight,
    borderRadius: spacing.md,
    padding: spacing.lg,
  },
  sendQRUserBadge: {
    position: 'absolute',
    bottom: -spacing.sm,
    width: spacing.xl,
    height: spacing.xl,
    borderRadius: spacing.md,
    backgroundColor: colors.textLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendQRUserBadgeText: {
    color: colors.brandGreen,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.bold,
  },
  sendQRContinueButton: {
    backgroundColor: colors.brandGreen,
    borderRadius: spacing.lg,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.xl,
    alignItems: 'center',
  },
  sendQRContinueButtonText: {
    color: colors.darkBackground,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
  },
  contactsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.cardBackground,
    borderRadius: spacing.lg,
    padding: spacing.md,
    marginBottom: spacing.md,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.border,
  },
  contactsButtonText: {
    flex: 1,
    marginLeft: spacing.sm,
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
  },
  // === MOCKUP AMOUNT CARD STYLES ===
  amountCardMockup: {
    borderRadius: 16,
    marginBottom: 24,
    alignItems: 'center',
    minHeight: 180,
    overflow: 'hidden',
  },
  amountCardHeader: {
    alignItems: 'center',
    backgroundColor: colors.white5,
    padding: 24,
    paddingBottom: 15,
    width: '100%',
    
  },
  amountCardLabel: {
    color: colors.white,
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 12,
  },
  amountCardInput: {
    color: colors.white,
    fontSize: 50,
    fontWeight: 'bold',
    textAlign: 'center',
    backgroundColor: 'transparent',
    borderWidth: 0,
    padding: 0,
    minWidth: 120,
    marginBottom: 10,
  },
  amountCardCurrency: {
    color: colors.white,
    fontSize: 22,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 0,
    marginBottom: 8,
  },

  amountCardAddNoteRow: {
    backgroundColor: colors.blackWhite5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    padding: 16,
  },
  amountCardAddNoteText: {
    color: colors.white50,
    fontSize: 15,
    marginLeft: 8,

  },
  amountCardNoteInputRow: {
    width: '100%',
    alignItems: 'center',
    marginTop: 0,
    marginBottom: 0,
    minHeight: 44,
    position: 'relative',
    paddingHorizontal: 10,
  },
  amountCardNoteInput: {
    color: colors.textLight,
    fontSize: 15,
    backgroundColor: 'transparent',
    borderWidth: 0,
    textAlign: 'center',
    minHeight: 44,
    width: '100%',
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  amountCardNoteCount: {
    color: colors.textSecondary,
    fontSize: 12,
    textAlign: 'right',
    width: '100%',
    marginTop: 2,
  },
  amountCardContinueButtonWrapper: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingTop: 8,
    alignItems: 'center',
    borderTopWidth: 0,

  },

  // AppleSlider styles (adapted from WalletManagement)
  appleSliderContainerWrapper: {
  },
  appleSliderGradientBorder: {
    borderRadius: 999,
    padding: 1,
    marginTop: 16,
    marginBottom: 8,
  },
  appleSliderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.blackWhite5,
    borderRadius: 999,
    position: 'relative',
    overflow: 'hidden',
    minHeight: 70,
    padding: 5,
    height: 70,
    // width: '100%', // supprimé pour éviter le débordement
  },
  appleSliderTrack: {
    flex: 1,
    height: 60,
    borderRadius: 999,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
  },
  appleSliderThumb: {
    position: 'absolute',
    left: 5,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: colors.brandGreen,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2,
  },
  appleSliderText: {
    color: colors.white50,
    fontSize: 17,
    fontWeight: '500',
    zIndex: 1,
    textAlign: 'center',
  },

  // === EXTERNAL WALLET STYLES ===
  emptyStateContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.screenPaddingHorizontal,
    paddingBottom: 100,
  },
  emptyStateIcon: {
    width: 70,
    height: 70,
    borderRadius: 40,
    backgroundColor: colors.white5,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.lg,
  },
  emptyStateIconText: {
    fontSize: 32,
  },
  emptyStateIconImage: {
    width: 32,
    height: 32,
  },
  emptyStateTitle: {
    color: colors.textLight,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.semibold,
    textAlign: 'center',
    marginBottom: spacing.sm,
  },
  emptyStateSubtitle: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.md,
    textAlign: 'center',
    lineHeight: spacing.lg,
    marginBottom: spacing.xl,
  },
  connectWalletButton: {
    backgroundColor: colors.brandGreen,
    borderRadius: spacing.md,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.xl,
    alignItems: 'center',
  },
  connectWalletButtonText: {
    color: colors.darkBackground,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
  },
  walletsList: {
    flex: 1,
  },
  walletRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white5,
    borderRadius: spacing.lg,
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  walletIcon: {
    width: spacing.xxl + spacing.sm,
    height: spacing.xxl + spacing.sm,
    borderRadius: spacing.xxl,
    backgroundColor: colors.white10,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
  },
  kastIcon: {
    width: spacing.xxl + spacing.sm,
    height: spacing.xxl + spacing.sm,
    borderRadius: spacing.xxl,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
  },
  walletIconText: {
    fontSize: typography.fontSize.md,
  },
  walletIconImage: {
    width: 20,
    height: 20,
  },
  walletInfo: {
    flex: 1,
  },
  walletName: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
    marginBottom: spacing.xs,
  },
  walletAddress: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
  },
  addWalletButton: {
    backgroundColor: colors.white10,
    borderRadius: spacing.md,
    padding: spacing.md,
    alignItems: 'center',
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.white10,
  },
  addWalletButtonText: {
    color: colors.textLight,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
  },

  // === QUICK AMOUNT CHIPS STYLES ===
  quickAmountChips: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  quickAmountChip: {
    backgroundColor: colors.white5,
    borderRadius: spacing.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderWidth: spacing.borderWidthThin,
    borderColor: colors.white50,
  },
  quickAmountChipSelected: {
    backgroundColor: colors.brandGreen,
    borderColor: colors.brandGreen,
  },
  quickAmountChipText: {
    color: colors.white70,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
  },
  quickAmountChipTextSelected: {
    color: colors.black,
    fontWeight: typography.fontWeight.semibold,
  },

}); 