#!/bin/bash

# WeSplit Dependency Cleanup Script
# Generated by audit-dependencies.js

echo "🧹 Cleaning up WeSplit dependencies..."

# Dependencies to remove from main package.json
UNUSED_DEPS=(
  "@emailjs/browser"
  "react-native-linear-gradient"
)

MISPLACED_DEPS=(
  "express"
  "firebase-admin" 
  "firebase-functions"
  "nodemailer"
  "pg"
  "cors"
  "dotenv"
)

echo "📦 Removing unused dependencies from main package..."
for dep in "${UNUSED_DEPS[@]}"; do
  echo "   Removing $dep..."
  npm uninstall "$dep"
done

echo "📦 Moving misplaced dependencies to backend..."
cd backend
for dep in "${MISPLACED_DEPS[@]}"; do
  echo "   Installing $dep in backend..."
  npm install "$dep"
done
cd ..

echo "📦 Removing misplaced dependencies from main package..."
for dep in "${MISPLACED_DEPS[@]}"; do
  echo "   Removing $dep from main package..."
  npm uninstall "$dep"
done

echo ""
echo "✅ Dependency cleanup complete!"
echo "📊 Estimated bundle size reduction: ~30MB"
echo "📊 Estimated install time reduction: ~7.5 seconds"
echo ""
echo "🔍 Next steps:"
echo "   1. Run 'npm install' to update lock file"
echo "   2. Test the application to ensure nothing broke"
echo "   3. Commit the changes"